//Add columns to USER_PROFILE_CONTRACT
ALTER TABLE USER_PROFILE_CONTRACT
ADD (AE_WEB_USER_ID NUMBER(8,0), 
	 MERGED VARCHAR2(5),
	 MERGE_TOKEN VARCHAR2(64 BYTE));
	 
//Add new "OLD_USERID" to personalization columns

ALTER TABLE TAG_GROUPS
ADD OLD_USER_ID VARCHAR(200);

ALTER TABLE TAGS
ADD OLD_USER_ID VARCHAR(200);

ALTER TABLE FOLDER
ADD OLD_USER_ID VARCHAR(200);

ALTER TABLE SEARCHES_SAVED
ADD OLD_USER_ID VARCHAR(200);

ALTER TABLE USER_PROFILE_CONTRACT
ADD (MERGED_WEB_USER_ID NUMBER(8,0));
	 

commit;