package org.ei.books.collections;

import java.util.LinkedList;
import java.util.List;

public class Che extends ReferexCollection {

	protected Che() {
	}

	public String getAbbrev() {
		// TODO Auto-generated method stub
		return "CHE";
	}

	public String getDisplayName() {
		// TODO Auto-generated method stub
		return "Chemical, Petrochemical & Process";
	}

	public String getShortname() {
		// TODO Auto-generated method stub
		return "Chemical";
	}

	  public List populateSubjects(boolean che, boolean chestar) {
	      List ches = new LinkedList();

	      if(!che && !chestar) {
	        ches.add("<HEAD><![CDATA[&#160;]]></HEAD>");
	        ches.add("<CV><![CDATA[&#160;<br/>]]></CV>");
	      } else if(che && !chestar) {
	        ches.add("<HEAD><![CDATA[<a class=\"SmWhiteText\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&col=Chemical\"><b>Chemical, Petrochemical & Process</b></a> <a class=\"SmWhiteText\">(100)</a>]]></HEAD>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Biomedical+Engineering}&section1=CV&boolean1=AND&col=CHE\">Biomedical Engineering (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Engineering}&section1=CV&boolean1=AND&col=CHE\">Chemical Engineering (46)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Health+and+Safety}&section1=CV&boolean1=AND&col=CHE\">Chemical Health and Safety (14)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemistry}&section1=CV&boolean1=AND&col=CHE\">Chemistry (16)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Civil+Engineering}&section1=CV&boolean1=AND&col=CHE\">Civil Engineering (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+Engineering}&section1=CV&boolean1=AND&col=CHE\">Control Engineering (3)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+of+Electrical+Systems}&section1=CV&boolean1=AND&col=CHE\">Control of Electrical Systems (3)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Design+Engineering}&section1=CV&boolean1=AND&col=CHE\">Design Engineering (3)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electromagnetics}&section1=CV&boolean1=AND&col=CHE\">Electromagnetics (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Energy+-+General}&section1=CV&boolean1=AND&col=CHE\">Energy - General (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Energy+Conservation+and+Environment}&section1=CV&boolean1=AND&col=CHE\">Energy Conservation and Environment (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Engineering+%28General%29}&section1=CV&boolean1=AND&col=CHE\">Engineering (General) (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Environmental+Assessment}&section1=CV&boolean1=AND&col=CHE\">Environmental Assessment (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Environmental+Engineering}&section1=CV&boolean1=AND&col=CHE\">Environmental Engineering (13)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Fluid+Dynamics}&section1=CV&boolean1=AND&col=CHE\">Fluid Dynamics (2)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Fluid+Mechanics}&section1=CV&boolean1=AND&col=CHE\">Fluid Mechanics (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Industrial+Health+and+Safety}&section1=CV&boolean1=AND&col=CHE\">Industrial Health and Safety (17)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+Processes+and+Systems}&section1=CV&boolean1=AND&col=CHE\">Manufacturing Processes and Systems (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+and+Instrumentation}&section1=CV&boolean1=AND&col=CHE\">Manufacturing and Instrumentation (4)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Engineering}&section1=CV&boolean1=AND&col=CHE\">Materials Engineering (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Science}&section1=CV&boolean1=AND&col=CHE\">Materials Science (4)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mathematics+for+Engineering}&section1=CV&boolean1=AND&col=CHE\">Mathematics for Engineering (2)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mechanical+Engineering}&section1=CV&boolean1=AND&col=CHE\">Mechanical Engineering (7)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Metallurgy+and+Metals+Processing}&section1=CV&boolean1=AND&col=CHE\">Metallurgy and Metals Processing (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Oil+Shales+and+Tar+Sands}&section1=CV&boolean1=AND&col=CHE\">Oil Shales and Tar Sands (6)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Petrochemical+Engineering}&section1=CV&boolean1=AND&col=CHE\">Petrochemical Engineering (25)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Petroleum%2C+Oil+Shales+and+Tar+Sands}&section1=CV&boolean1=AND&col=CHE\">Petroleum, Oil Shales and Tar Sands (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Pipeline+Technology}&section1=CV&boolean1=AND&col=CHE\">Pipeline Technology (7)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Plant+Maintenance}&section1=CV&boolean1=AND&col=CHE\">Plant Maintenance (3)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Control}&section1=CV&boolean1=AND&col=CHE\">Process Control (5)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Design}&section1=CV&boolean1=AND&col=CHE\">Process Design (5)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Production+Management}&section1=CV&boolean1=AND&col=CHE\">Production Management (5)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Quality+Systems+%2F+Quality+Assurance}&section1=CV&boolean1=AND&col=CHE\">Quality Systems / Quality Assurance (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Resource+Management}&section1=CV&boolean1=AND&col=CHE\">Resource Management (2)</a><br/>]]></CV>");
	      } else if(che && chestar) {
	        ches.add("<HEAD><![CDATA[<a class=\"SmWhiteText\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&col=Chemical\"><b>Chemical, Petrochemical & Process</b></a> <a class=\"SmWhiteText\">(114)</a>]]></HEAD>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Biomedical+Engineering}&section1=CV&boolean1=AND&col=CHE\">Biomedical Engineering (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Engineering}&section1=CV&boolean1=AND&col=CHE\">Chemical Engineering (46)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Health+and+Safety}&section1=CV&boolean1=AND&col=CHE\">Chemical Health and Safety (14)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemistry}&section1=CV&boolean1=AND&col=CHE\">Chemistry (16)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Civil+Engineering}&section1=CV&boolean1=AND&col=CHE\">Civil Engineering (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+Engineering}&section1=CV&boolean1=AND&col=CHE\">Control Engineering (3)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+of+Electrical+Systems}&section1=CV&boolean1=AND&col=CHE\">Control of Electrical Systems (3)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Design+Engineering}&section1=CV&boolean1=AND&col=CHE\">Design Engineering (3)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electromagnetics}&section1=CV&boolean1=AND&col=CHE\">Electromagnetics (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Energy+-+General}&section1=CV&boolean1=AND&col=CHE\">Energy - General (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Energy+Conservation+and+Environment}&section1=CV&boolean1=AND&col=CHE\">Energy Conservation and Environment (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Engineering+%28General%29}&section1=CV&boolean1=AND&col=CHE\">Engineering (General) (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Environmental+Assessment}&section1=CV&boolean1=AND&col=CHE\">Environmental Assessment (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Environmental+Engineering}&section1=CV&boolean1=AND&col=CHE\">Environmental Engineering (13)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Fluid+Dynamics}&section1=CV&boolean1=AND&col=CHE\">Fluid Dynamics (2)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Fluid+Mechanics}&section1=CV&boolean1=AND&col=CHE\">Fluid Mechanics (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Industrial+Health+and+Safety}&section1=CV&boolean1=AND&col=CHE\">Industrial Health and Safety (17)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+Processes+and+Systems}&section1=CV&boolean1=AND&col=CHE\">Manufacturing Processes and Systems (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+and+Instrumentation}&section1=CV&boolean1=AND&col=CHE\">Manufacturing and Instrumentation (4)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Engineering}&section1=CV&boolean1=AND&col=CHE\">Materials Engineering (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Science}&section1=CV&boolean1=AND&col=CHE\">Materials Science (4)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mathematics+for+Engineering}&section1=CV&boolean1=AND&col=CHE\">Mathematics for Engineering (2)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mechanical+Engineering}&section1=CV&boolean1=AND&col=CHE\">Mechanical Engineering (7)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Metallurgy+and+Metals+Processing}&section1=CV&boolean1=AND&col=CHE\">Metallurgy and Metals Processing (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Oil+Shales+and+Tar+Sands}&section1=CV&boolean1=AND&col=CHE\">Oil Shales and Tar Sands (6)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Petrochemical+Engineering}&section1=CV&boolean1=AND&col=CHE\">Petrochemical Engineering (25)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Petroleum%2C+Oil+Shales+and+Tar+Sands}&section1=CV&boolean1=AND&col=CHE\">Petroleum, Oil Shales and Tar Sands (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Pipeline+Technology}&section1=CV&boolean1=AND&col=CHE\">Pipeline Technology (7)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Plant+Maintenance}&section1=CV&boolean1=AND&col=CHE\">Plant Maintenance (3)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Control}&section1=CV&boolean1=AND&col=CHE\">Process Control (5)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Design}&section1=CV&boolean1=AND&col=CHE\">Process Design (5)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Production+Management}&section1=CV&boolean1=AND&col=CHE\">Production Management (5)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Quality+Systems+%2F+Quality+Assurance}&section1=CV&boolean1=AND&col=CHE\">Quality Systems / Quality Assurance (1)</a><br/>]]></CV>");
	        ches.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Resource+Management}&section1=CV&boolean1=AND&col=CHE\">Resource Management (2)</a><br/>]]></CV>");
	      }
	    return ches;
	   }
	
}
