package org.ei.books.collections;

import java.util.LinkedList;
import java.util.List;


public class Ele extends ReferexCollection {

	protected Ele() {
	}
	

	public String getAbbrev() {
		// TODO Auto-generated method stub
		return "ELE";
	}

	public String getDisplayName() {
		// TODO Auto-generated method stub
		return "Electronics & Electrical";
	}

	public String getShortname() {
		// TODO Auto-generated method stub
		return "Electronics";
	}
	public List populateSubjects(boolean ele, boolean elestar) {
	      List eles = new LinkedList();
	      if(!ele && !elestar) {
	        eles.add("<HEAD><![CDATA[&#160;]]></HEAD>");
	        eles.add("<CV><![CDATA[&#160;<br/>]]></CV>");
	      } else if(ele && !elestar) {
	        eles.add("<HEAD><![CDATA[<a class=\"SmWhiteText\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&col=Electronics\"><b>Electronics & Electrical</b></a> <a class=\"SmWhiteText\">(120)</a>]]></HEAD>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Audio+Electronics}&section1=CV&boolean1=AND&col=ELE\">Audio Electronics (4)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Biomedical+Engineering}&section1=CV&boolean1=AND&col=ELE\">Biomedical Engineering (2)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Health+and+Safety}&section1=CV&boolean1=AND&col=ELE\">Chemical Health and Safety (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Circuit+Design}&section1=CV&boolean1=AND&col=ELE\">Circuit Design (17)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Circuit+Theory+and+Analysis}&section1=CV&boolean1=AND&col=ELE\">Circuit Theory and Analysis (6)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Communications+and+Signal+Processing}&section1=CV&boolean1=AND&col=ELE\">Communications and Signal Processing (32)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Computer+Interfacing}&section1=CV&boolean1=AND&col=ELE\">Computer Interfacing (6)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Computing+for+Engineers}&section1=CV&boolean1=AND&col=ELE\">Computing for Engineers (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+Applications}&section1=CV&boolean1=AND&col=ELE\">Control Applications (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+Engineering}&section1=CV&boolean1=AND&col=ELE\">Control Engineering (6)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+of+Electrical+Systems}&section1=CV&boolean1=AND&col=ELE\">Control of Electrical Systems (8)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Digital+Signal+Processing}&section1=CV&boolean1=AND&col=ELE\">Digital Signal Processing (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={EMC+%2F+EMI}&section1=CV&boolean1=AND&col=ELE\">EMC / EMI (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electrical+Engineering}&section1=CV&boolean1=AND&col=ELE\">Electrical Engineering (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electrical+Machines+and+Drives}&section1=CV&boolean1=AND&col=ELE\">Electrical Machines and Drives (4)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electrical+Power+and+Distribution}&section1=CV&boolean1=AND&col=ELE\">Electrical Power and Distribution (11)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electromagnetics}&section1=CV&boolean1=AND&col=ELE\">Electromagnetics (28)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electromagnetics%2C+Signal+Processing+and+Communications}&section1=CV&boolean1=AND&col=ELE\">Electromagnetics, Signal Processing and Communications (2)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronic+Devices+and+Materials}&section1=CV&boolean1=AND&col=ELE\">Electronic Devices and Materials (7)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronic+Security}&section1=CV&boolean1=AND&col=ELE\">Electronic Security (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronics+%28General%29}&section1=CV&boolean1=AND&col=ELE\">Electronics (General) (2)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronics+Manufacturing+and+Testing}&section1=CV&boolean1=AND&col=ELE\">Electronics Manufacturing and Testing (7)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Embedded+Systems}&section1=CV&boolean1=AND&col=ELE\">Embedded Systems (14)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Image+and+Video+Processing}&section1=CV&boolean1=AND&col=ELE\">Image and Video Processing (4)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Industrial+Health+and+Safety}&section1=CV&boolean1=AND&col=ELE\">Industrial Health and Safety (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+Processes+and+Systems}&section1=CV&boolean1=AND&col=ELE\">Manufacturing Processes and Systems (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+and+Instrumentation}&section1=CV&boolean1=AND&col=ELE\">Manufacturing and Instrumentation (9)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Marine+Engineering}&section1=CV&boolean1=AND&col=ELE\">Marine Engineering (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Mechanics}&section1=CV&boolean1=AND&col=ELE\">Materials Mechanics (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Science}&section1=CV&boolean1=AND&col=ELE\">Materials Science (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mathematics+for+Engineering}&section1=CV&boolean1=AND&col=ELE\">Mathematics for Engineering (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mechanical+Engineering}&section1=CV&boolean1=AND&col=ELE\">Mechanical Engineering (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Microelectronics}&section1=CV&boolean1=AND&col=ELE\">Microelectronics (26)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Optical+Engineering+%2F+Optics}&section1=CV&boolean1=AND&col=ELE\">Optical Engineering / Optics (16)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Optics}&section1=CV&boolean1=AND&col=ELE\">Optics (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Optics+and+Lasers}&section1=CV&boolean1=AND&col=ELE\">Optics and Lasers (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Power+Electronics}&section1=CV&boolean1=AND&col=ELE\">Power Electronics (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Quality+Systems+%2F+Quality+Assurance}&section1=CV&boolean1=AND&col=ELE\">Quality Systems / Quality Assurance (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Robotics}&section1=CV&boolean1=AND&col=ELE\">Robotics (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Software+Engineering}&section1=CV&boolean1=AND&col=ELE\">Software Engineering (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Telecommunications}&section1=CV&boolean1=AND&col=ELE\">Telecommunications (18)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Video+and+Television}&section1=CV&boolean1=AND&col=ELE\">Video and Television (4)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Wireless+Communications}&section1=CV&boolean1=AND&col=ELE\">Wireless Communications (3)</a><br/>]]></CV>");
	      } else if(ele && elestar) {
	        eles.add("<HEAD><![CDATA[<a class=\"SmWhiteText\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&&col=Electronics\"><b>Electronics & Electrical</b></a> <a class=\"SmWhiteText\">(138)</a>]]></HEAD>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Audio+Electronics}&section1=CV&boolean1=AND&col=ELE\">Audio Electronics (4)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Biomedical+Engineering}&section1=CV&boolean1=AND&col=ELE\">Biomedical Engineering (2)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Health+and+Safety}&section1=CV&boolean1=AND&col=ELE\">Chemical Health and Safety (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Circuit+Design}&section1=CV&boolean1=AND&col=ELE\">Circuit Design (17)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Circuit+Theory+and+Analysis}&section1=CV&boolean1=AND&col=ELE\">Circuit Theory and Analysis (6)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Communications+and+Signal+Processing}&section1=CV&boolean1=AND&col=ELE\">Communications and Signal Processing (32)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Computer+Interfacing}&section1=CV&boolean1=AND&col=ELE\">Computer Interfacing (6)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Computing+for+Engineers}&section1=CV&boolean1=AND&col=ELE\">Computing for Engineers (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+Applications}&section1=CV&boolean1=AND&col=ELE\">Control Applications (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+Engineering}&section1=CV&boolean1=AND&col=ELE\">Control Engineering (6)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+of+Electrical+Systems}&section1=CV&boolean1=AND&col=ELE\">Control of Electrical Systems (8)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Digital+Signal+Processing}&section1=CV&boolean1=AND&col=ELE\">Digital Signal Processing (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={EMC+%2F+EMI}&section1=CV&boolean1=AND&col=ELE\">EMC / EMI (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electrical+Engineering}&section1=CV&boolean1=AND&col=ELE\">Electrical Engineering (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electrical+Machines+and+Drives}&section1=CV&boolean1=AND&col=ELE\">Electrical Machines and Drives (4)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electrical+Power+and+Distribution}&section1=CV&boolean1=AND&col=ELE\">Electrical Power and Distribution (11)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electromagnetics}&section1=CV&boolean1=AND&col=ELE\">Electromagnetics (28)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electromagnetics%2C+Signal+Processing+and+Communications}&section1=CV&boolean1=AND&col=ELE\">Electromagnetics, Signal Processing and Communications (2)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronic+Devices+and+Materials}&section1=CV&boolean1=AND&col=ELE\">Electronic Devices and Materials (7)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronic+Security}&section1=CV&boolean1=AND&col=ELE\">Electronic Security (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronics+%28General%29}&section1=CV&boolean1=AND&col=ELE\">Electronics (General) (2)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronics+Manufacturing+and+Testing}&section1=CV&boolean1=AND&col=ELE\">Electronics Manufacturing and Testing (7)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Embedded+Systems}&section1=CV&boolean1=AND&col=ELE\">Embedded Systems (14)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Image+and+Video+Processing}&section1=CV&boolean1=AND&col=ELE\">Image and Video Processing (4)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Industrial+Health+and+Safety}&section1=CV&boolean1=AND&col=ELE\">Industrial Health and Safety (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+Processes+and+Systems}&section1=CV&boolean1=AND&col=ELE\">Manufacturing Processes and Systems (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+and+Instrumentation}&section1=CV&boolean1=AND&col=ELE\">Manufacturing and Instrumentation (9)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Marine+Engineering}&section1=CV&boolean1=AND&col=ELE\">Marine Engineering (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Mechanics}&section1=CV&boolean1=AND&col=ELE\">Materials Mechanics (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Science}&section1=CV&boolean1=AND&col=ELE\">Materials Science (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mathematics+for+Engineering}&section1=CV&boolean1=AND&col=ELE\">Mathematics for Engineering (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mechanical+Engineering}&section1=CV&boolean1=AND&col=ELE\">Mechanical Engineering (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Microelectronics}&section1=CV&boolean1=AND&col=ELE\">Microelectronics (26)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Optical+Engineering+%2F+Optics}&section1=CV&boolean1=AND&col=ELE\">Optical Engineering / Optics (16)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Optics}&section1=CV&boolean1=AND&col=ELE\">Optics (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Optics+and+Lasers}&section1=CV&boolean1=AND&col=ELE\">Optics and Lasers (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Power+Electronics}&section1=CV&boolean1=AND&col=ELE\">Power Electronics (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Quality+Systems+%2F+Quality+Assurance}&section1=CV&boolean1=AND&col=ELE\">Quality Systems / Quality Assurance (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Robotics}&section1=CV&boolean1=AND&col=ELE\">Robotics (1)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Software+Engineering}&section1=CV&boolean1=AND&col=ELE\">Software Engineering (3)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Telecommunications}&section1=CV&boolean1=AND&col=ELE\">Telecommunications (18)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Video+and+Television}&section1=CV&boolean1=AND&col=ELE\">Video and Television (4)</a><br/>]]></CV>");
	        eles.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Wireless+Communications}&section1=CV&boolean1=AND&col=ELE\">Wireless Communications (3)</a><br/>]]></CV>");
	      }
	      return eles;
	    }

}
