package org.ei.books.collections;

import java.util.LinkedList;
import java.util.List;

public class Mat extends ReferexCollection {

	protected Mat() {
	}

	public String getAbbrev() {
		// TODO Auto-generated method stub
		return "MAT";
	}

	public String getDisplayName() {
		// TODO Auto-generated method stub
		return "Materials & Mechanical";
	}

	public String getShortname() {
		// TODO Auto-generated method stub
		return "Materials";
	}
	public List populateSubjects(boolean mat, boolean matstar) {
	      List mats = new LinkedList();
	      if(!mat && !matstar) {
	        mats.add("<HEAD><![CDATA[&#160;]]></HEAD>");
	        mats.add("<CV><![CDATA[&#160;<br/>]]></CV>");
	      } else if(mat && !matstar) {
	        mats.add("<HEAD><![CDATA[<a class=\"SmWhiteText\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&col=Materials\"><b>Materials & Mechanical</b></a> <a class=\"SmWhiteText\">(133)</a>]]></HEAD>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Aeronautical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Aeronautical Engineering (7)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Aircraft+Design}&section1=CV&boolean1=AND&col=MAT\">Aircraft Design (6)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Automotive+Engineering}&section1=CV&boolean1=AND&col=MAT\">Automotive Engineering (10)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Biomedical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Biomedical Engineering (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Business+Strategy+and+Industrial+Engineering}&section1=CV&boolean1=AND&col=MAT\">Business Strategy and Industrial Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={CAD%2C+CAM%2C+CAE}&section1=CV&boolean1=AND&col=MAT\">CAD, CAM, CAE (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Chemical Engineering (7)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Health+and+Safety}&section1=CV&boolean1=AND&col=MAT\">Chemical Health and Safety (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Civil+Engineering}&section1=CV&boolean1=AND&col=MAT\">Civil Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Computer+Aided+Design}&section1=CV&boolean1=AND&col=MAT\">Computer Aided Design (5)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Computing+for+Engineers}&section1=CV&boolean1=AND&col=MAT\">Computing for Engineers (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+Engineering}&section1=CV&boolean1=AND&col=MAT\">Control Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+of+Electrical+Systems}&section1=CV&boolean1=AND&col=MAT\">Control of Electrical Systems (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Design+Engineering}&section1=CV&boolean1=AND&col=MAT\">Design Engineering (8)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electrical+Installation}&section1=CV&boolean1=AND&col=MAT\">Electrical Installation (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronics+Manufacturing+and+Testing}&section1=CV&boolean1=AND&col=MAT\">Electronics Manufacturing and Testing (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronics+Servicing+and+Repair}&section1=CV&boolean1=AND&col=MAT\">Electronics Servicing and Repair (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Engineering+%28General%29}&section1=CV&boolean1=AND&col=MAT\">Engineering (General) (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Engineering+Drawing}&section1=CV&boolean1=AND&col=MAT\">Engineering Drawing (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Environmental+Engineering}&section1=CV&boolean1=AND&col=MAT\">Environmental Engineering (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Facilities+Maintenance}&section1=CV&boolean1=AND&col=MAT\">Facilities Maintenance (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Finite+Element+Method+%2F+Modelling}&section1=CV&boolean1=AND&col=MAT\">Finite Element Method / Modelling (4)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Fluid+Dynamics}&section1=CV&boolean1=AND&col=MAT\">Fluid Dynamics (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Fluid+Mechanics}&section1=CV&boolean1=AND&col=MAT\">Fluid Mechanics (3)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Industrial+Health+and+Safety}&section1=CV&boolean1=AND&col=MAT\">Industrial Health and Safety (5)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+Processes+and+Systems}&section1=CV&boolean1=AND&col=MAT\">Manufacturing Processes and Systems (3)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+and+Instrumentation}&section1=CV&boolean1=AND&col=MAT\">Manufacturing and Instrumentation (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Marine+Engineering}&section1=CV&boolean1=AND&col=MAT\">Marine Engineering (19)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Engineering}&section1=CV&boolean1=AND&col=MAT\">Materials Engineering (16)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Mechanics}&section1=CV&boolean1=AND&col=MAT\">Materials Mechanics (3)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Science}&section1=CV&boolean1=AND&col=MAT\">Materials Science (12)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mathematics+for+Engineering}&section1=CV&boolean1=AND&col=MAT\">Mathematics for Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mechanical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Mechanical Engineering (64)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Metallurgy+and+Metals+Processing}&section1=CV&boolean1=AND&col=MAT\">Metallurgy and Metals Processing (12)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Naval+Architecture}&section1=CV&boolean1=AND&col=MAT\">Naval Architecture (11)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Optical+Engineering+%2F+Optics}&section1=CV&boolean1=AND&col=MAT\">Optical Engineering / Optics (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Petrochemical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Petrochemical Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Pipeline+Technology}&section1=CV&boolean1=AND&col=MAT\">Pipeline Technology (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Plant+Maintenance}&section1=CV&boolean1=AND&col=MAT\">Plant Maintenance (8)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Control}&section1=CV&boolean1=AND&col=MAT\">Process Control (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Design}&section1=CV&boolean1=AND&col=MAT\">Process Design (4)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Design%2C+Simulation%2C+Control}&section1=CV&boolean1=AND&col=MAT\">Process Design, Simulation, Control (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Production}&section1=CV&boolean1=AND&col=MAT\">Production (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Production+Management}&section1=CV&boolean1=AND&col=MAT\">Production Management (14)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Quality+Systems+%2F+Quality+Assurance}&section1=CV&boolean1=AND&col=MAT\">Quality Systems / Quality Assurance (7)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Robotics}&section1=CV&boolean1=AND&col=MAT\">Robotics (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Ship+Operations}&section1=CV&boolean1=AND&col=MAT\">Ship Operations (4)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Strategy+and+Strategic+Management}&section1=CV&boolean1=AND&col=MAT\">Strategy and Strategic Management (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Tribology}&section1=CV&boolean1=AND&col=MAT\">Tribology (3)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Video+and+Television}&section1=CV&boolean1=AND&col=MAT\">Video and Television (1)</a><br/>]]></CV>");
	      } else if(mat && matstar) {
	        mats.add("<HEAD><![CDATA[<a class=\"SmWhiteText\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&col=Materials\"><b>Materials & Mechanical</b></a> <a class=\"SmWhiteText\">(155)</a>]]></HEAD>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Aeronautical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Aeronautical Engineering (7)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Aircraft+Design}&section1=CV&boolean1=AND&col=MAT\">Aircraft Design (6)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Automotive+Engineering}&section1=CV&boolean1=AND&col=MAT\">Automotive Engineering (10)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Biomedical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Biomedical Engineering (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Business+Strategy+and+Industrial+Engineering}&section1=CV&boolean1=AND&col=MAT\">Business Strategy and Industrial Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={CAD%2C+CAM%2C+CAE}&section1=CV&boolean1=AND&col=MAT\">CAD, CAM, CAE (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Chemical Engineering (7)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Chemical+Health+and+Safety}&section1=CV&boolean1=AND&col=MAT\">Chemical Health and Safety (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Civil+Engineering}&section1=CV&boolean1=AND&col=MAT\">Civil Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Computer+Aided+Design}&section1=CV&boolean1=AND&col=MAT\">Computer Aided Design (5)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Computing+for+Engineers}&section1=CV&boolean1=AND&col=MAT\">Computing for Engineers (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+Engineering}&section1=CV&boolean1=AND&col=MAT\">Control Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Control+of+Electrical+Systems}&section1=CV&boolean1=AND&col=MAT\">Control of Electrical Systems (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Design+Engineering}&section1=CV&boolean1=AND&col=MAT\">Design Engineering (8)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electrical+Installation}&section1=CV&boolean1=AND&col=MAT\">Electrical Installation (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronics+Manufacturing+and+Testing}&section1=CV&boolean1=AND&col=MAT\">Electronics Manufacturing and Testing (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Electronics+Servicing+and+Repair}&section1=CV&boolean1=AND&col=MAT\">Electronics Servicing and Repair (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Engineering+%28General%29}&section1=CV&boolean1=AND&col=MAT\">Engineering (General) (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Engineering+Drawing}&section1=CV&boolean1=AND&col=MAT\">Engineering Drawing (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Environmental+Engineering}&section1=CV&boolean1=AND&col=MAT\">Environmental Engineering (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Facilities+Maintenance}&section1=CV&boolean1=AND&col=MAT\">Facilities Maintenance (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Finite+Element+Method+%2F+Modelling}&section1=CV&boolean1=AND&col=MAT\">Finite Element Method / Modelling (4)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Fluid+Dynamics}&section1=CV&boolean1=AND&col=MAT\">Fluid Dynamics (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Fluid+Mechanics}&section1=CV&boolean1=AND&col=MAT\">Fluid Mechanics (3)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Industrial+Health+and+Safety}&section1=CV&boolean1=AND&col=MAT\">Industrial Health and Safety (5)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+Processes+and+Systems}&section1=CV&boolean1=AND&col=MAT\">Manufacturing Processes and Systems (3)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Manufacturing+and+Instrumentation}&section1=CV&boolean1=AND&col=MAT\">Manufacturing and Instrumentation (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Marine+Engineering}&section1=CV&boolean1=AND&col=MAT\">Marine Engineering (19)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Engineering}&section1=CV&boolean1=AND&col=MAT\">Materials Engineering (16)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Mechanics}&section1=CV&boolean1=AND&col=MAT\">Materials Mechanics (3)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Materials+Science}&section1=CV&boolean1=AND&col=MAT\">Materials Science (12)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mathematics+for+Engineering}&section1=CV&boolean1=AND&col=MAT\">Mathematics for Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Mechanical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Mechanical Engineering (64)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Metallurgy+and+Metals+Processing}&section1=CV&boolean1=AND&col=MAT\">Metallurgy and Metals Processing (12)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Naval+Architecture}&section1=CV&boolean1=AND&col=MAT\">Naval Architecture (11)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Optical+Engineering+%2F+Optics}&section1=CV&boolean1=AND&col=MAT\">Optical Engineering / Optics (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Petrochemical+Engineering}&section1=CV&boolean1=AND&col=MAT\">Petrochemical Engineering (2)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Pipeline+Technology}&section1=CV&boolean1=AND&col=MAT\">Pipeline Technology (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Plant+Maintenance}&section1=CV&boolean1=AND&col=MAT\">Plant Maintenance (8)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Control}&section1=CV&boolean1=AND&col=MAT\">Process Control (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Design}&section1=CV&boolean1=AND&col=MAT\">Process Design (4)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Process+Design%2C+Simulation%2C+Control}&section1=CV&boolean1=AND&col=MAT\">Process Design, Simulation, Control (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Production}&section1=CV&boolean1=AND&col=MAT\">Production (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Production+Management}&section1=CV&boolean1=AND&col=MAT\">Production Management (14)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Quality+Systems+%2F+Quality+Assurance}&section1=CV&boolean1=AND&col=MAT\">Quality Systems / Quality Assurance (7)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Robotics}&section1=CV&boolean1=AND&col=MAT\">Robotics (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Ship+Operations}&section1=CV&boolean1=AND&col=MAT\">Ship Operations (4)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Strategy+and+Strategic+Management}&section1=CV&boolean1=AND&col=MAT\">Strategy and Strategic Management (1)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Tribology}&section1=CV&boolean1=AND&col=MAT\">Tribology (3)</a><br/>]]></CV>");
	        mats.add("<CV><![CDATA[<a class=\"SpLink\" href=\"/controller/servlet/Controller?database=131072&sortdir=up&sort=stsort&yearselect=yearrange&CID=quickSearchCitationFormat&searchtype=Book&searchWord1={Video+and+Television}&section1=CV&boolean1=AND&col=MAT\">Video and Television (1)</a><br/>]]></CV>");
	      }
	      return mats;
	    }

}
