package org.ei.service.cars;


public enum CARSAuthenticationConstants {

	SESSION_AFFINITY_KEY("JSESSIONID"),
	REQUEST_PARAMS_HOLDER("requestParams"),
	SET_COOKIE("Set-Cookie"),
	USER_LOGGED_OUT_BY_SSO("USER_LOGGED_OUT_BY_SSO"),
	SSO_COOKIE("acw"),
	SSO_PARAM_KEY("acwredir"),
	SSO_SESSION_KEY("SSO_KEY"),
	SSO_SESSION_TIMESTAMP("SSOTIMESTAMP"),
	SSO_URLS("SSO_URLS"),
	AUTH_TOKEN("AUTH_TOKEN"),
	LOGOUT("LOGOUT"),
	SSO_COOKIE_VALUE_SET("SSOCookieValueSet"),
	IS_SSO_REVALIDATE_REQ("IS_SSO_REVALIDATE_REQ"),
	USER_ANONYMITY("USER_ANONYMITY"),
	PATH_CHOICE("PATH_CHOICE"),
	STATE_CHANGE("STATECHANGE"),
	SSO_CSAS_ERROR("SSO_CSAS_ERROR"),
	CARS_LAST_SUCESS_ACCESS_TIME("CARS_LAST_SUCESS_ACCESS_TIME"),
	HTTP_METHOD_NAME("http_method_name"),
	CARS_COOKIE_NAME("CARS_COOKIE"),
	USER_ANONYMITY_TYPE_COOKIE("USER_ANONYMITY_TYPE_COOKIE"),
	USER_AUTH_TOKEN_COOKIE("USER_AUTH_TOKEN_COOKIE"),
	SESSIONID_COOKIE("SESSIONID_COOKIE"),
	REVALIDATE_IP("REVALIDATE_IP"),
	INDIVIDUAL("INDIVIDUAL"),
	ANON_SHIBBOLETH("ANON_SHIBBOLETH"),
	PREVIOUS_URL("PREVIOUS_URL"),
    CANDIDATE_PATH("CANDIDATE_PATH"),
    AUTHTOKEN_COOKIE_NAME("RXSESSION"),;

	private final String m_value;

	private CARSAuthenticationConstants(String str) {
		this.m_value = str;
	}

	public String value() {
		return m_value;
	}
}

