/*
 * Created on Aug 26, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package org.ei.common;

import java.util.Enumeration;
import java.util.Hashtable;

import org.apache.oro.text.perl.Perl5Util;

/**
 * @author Tsolovye
 *
 *         TODO To change the template for this generated type comment go to Window - Preferences - Java - Code Style - Code Templates
 */
public class Country {

    public static final String ARIPO = "aripo";
    public static final String ARUBA = "aruba";
    public static final String CHRISTMAS_ISLAND = "christmas island";
    public static final String BOUVET_ISLAND = "bouvet island";
    public static final String EURASIAN_PTO = "eurasian patent office";
    public static final String EUROPIAN_PTO = "european patent office";
    public static final String FRANCE_METRO = "france, metropolitan";
    public static final String GULF_COOP = "gulf cooperation council";
    public static final String SOUTH_GEO = "south georgia and the south sandwich islands";
    public static final String GUINEA_BISS = "guinea-bissau";
    public static final String HEARD_MCDI = "heard & mcDonald islands";
    public static final String COMOROS = "comoros";
    public static final String SAINT_KITTS = "st. kitts and nevis";
    public static final String SAINT_LUCIA = "saint lucia";
    public static final String NORTH_MARIANA = "northern mariana islands";
    public static final String MONSERRAT = "monserrat";
    public static final String NEUTRAL_ZONE = "neutral zone";
    public static final String OAPI = "oapi";
    public static final String SAINT_PIERRE = "st. pierre & miquelon";
    public static final String PALAU = "Palau";
    public static final String SAINT_HELENA = "st. helena";
    public static final String FRENCH_SOUTH = "french southern territories";
    public static final String EAST_TIMOR = "east timor";
    public static final String US_VIRGIN_ISLANDS = "united states virgin islands";
    public static final String WIPO = "wipo";
    public static final String MAYOTTE = "mayotte";
    public static final String ARGENTINA = "argentina";
    public static final String ANTARCTICA = "antarctica";
    public static final String AFGHANISTAN = "afghanistan";
    public static final String ANTIGUA = "antigua";
    public static final String US = "united states";
    public static final String ALBANIA = "albania";
    public static final String CANADA = "canada";
    public static final String ALGERIA = "algeria";
    public static final String ARMENIA = "armenia";
    public static final String ANDORRA = "andorra";
    public static final String ANGOLA = "angola";
    public static final String GREECE = "greece";
    public static final String AUSTRIA = "austria";
    public static final String AUSTRALIA = "australia";
    public static final String AZERBAIJAN = "azerbaijan";
    public static final String BELGIUM = "belgium";
    public static final String BELARUS = "belarus";
    public static final String BAHAMAS = "bahamas";
    public static final String BAHRAIN = "bahrain";
    public static final String BENIN = "benin";
    public static final String BANGLADESH = "bangladesh";
    public static final String BARBADOS = "barbados";
    public static final String SPAIN = "spain";
    public static final String CHINA = "china";
    public static final String BELIZE = "belize";
    public static final String BERMUDA = "bermuda";
    public static final String BHUTAN = "bhutan";
    public static final String BOLIVIA = "bolivia";
    public static final String ITALY = "italy";
    public static final String INDIA = "india";
    public static final String BOSNIA = "bosnia and herzegovina";
    public static final String BOTSWANA = "botswana";
    public static final String BRAZIL = "brazil";
    public static final String BRUNIE = "brunie";
    public static final String UK = "united kingdom";
    public static final String BVI = "british virgin islands";
    public static final String BRUNEI = "brunei";
    public static final String BULGARIA = "bulgaria";
    public static final String BURMA = "burma";
    public static final String BURUNDI = "burundi";
    public static final String COLOMBIA = "colombia";
    public static final String COSTA = "costa rica";
    public static final String CZECH = "czechoslovakia";
    public static final String CZECH_REP = "czech republic";
    public static final String EGYPT = "egypt";
    public static final String CAMBODIA = "cambodia";
    public static final String CAMEROON = "cameroon";
    public static final String CAYMAN = "cayman islands";
    public static final String CAR = "central african republic";
    public static final String CHAD = "chad";
    public static final String CHILE = "chile";
    public static final String CONGO = "congo";
    public static final String CROATIA = "croatia";
    public static final String COOK_ISLANDS = "cook islands";
    public static final String CUBA = "cuba";
    public static final String CYPRUS = "cyprus";
    public static final String DENMARK = "denmark";
    public static final String DOMINICAN = "dominican republic";
    public static final String DOMINICA = "dominica";
    public static final String DJIBOUTI = "djibouti";
    public static final String ECUADOR = "ecuador";
    public static final String ELSAL = "el salvador";
    public static final String EQUATORIAL_GUINEA = "equatorial guinea";
    public static final String ERITREA = "eritrea";
    public static final String ESTONIA = "estonia";
    public static final String ETHIOPIA = "ethiopia";
    public static final String FINLAND = "finland";
    public static final String FRANCE = "france";
    public static final String FAROE_ISLANDS = "faroe islands";
    public static final String FALKLAND_ISLANDS = "falkland islands";
    public static final String FRENCH_GUIANA = "french guiana";
    public static final String FRENCH_POLYNESIA = "french polynesia";
    public static final String FIJI = "fiji";
    public static final String GAMBIA = "gambia";
    public static final String GABON = "gabon";
    public static final String GERMANY = "germany";
    public static final String GHANA = "ghana";
    public static final String LUXEMBOURG = "luxembourg";
    public static final String GREENLAND = "greenland";
    public static final String GRENADA = "grenada";
    public static final String GUADELOUPE = "guadeloupe";
    public static final String GUYANA = "guyana";
    public static final String GEORGIA = "georgia";
    public static final String GUAM = "guam";
    public static final String GUATEMALA = "guatemala";
    public static final String GUADALOUPE = "guadaloupe";
    public static final String GIBRALTAR = "gibraltar";
    public static final String GUINEA = "guinea";
    public static final String NETHERLANDS = "netherlands";
    public static final String NETHERLANDS_ANTILLES = "netherlands antilles";
    public static final String HONDURAS = "honduras";
    public static final String HONG_KONG = "hong kong";
    public static final String HUNGARY = "hungary";
    public static final String ISRAEL = "israel";
    public static final String ICELAND = "iceland";
    public static final String INDONESIA = "indonesia";
    public static final String IRAN = "iran";
    public static final String IRAQ = "iraq";
    public static final String IRELAND = "ireland";
    public static final String TURKEY = "turkey";
    public static final String IVORY_COAST = "ivory coast";
    public static final String JAPAN = "japan";
    public static final String JAMAICA = "jamaica";
    public static final String JORDAN = "jordan";
    public static final String YUGOSLAVIA = "yugoslavia";
    public static final String KAZAKHSTAN = "kazakhstan";
    public static final String KAMPUCHEA = "kampuchea";
    public static final String KENYA = "kenya";
    public static final String ROMANIA = "romania";
    public static final String RUSSIA = "russia";
    public static final String SOUTH_AFRICA = "south africa";
    public static final String SAUDI_ARABIA = "saudi arabia";
    public static final String SWITZERLAND = "switzerland";
    public static final String SWEDEN = "sweden";
    public static final String UKRAINE = "ukraine";
    public static final String KYRGYZSTAN = "kyrgyzstan";
    public static final String SKOREA = "korea, republic of";
    public static final String HAITI = "haiti";
    public static final String KUWAIT = "kuwait";
    public static final String KAMPUCHE = "kampuche";
    public static final String KIRIBATI = "kiribati";
    public static final String LATVIA = "latvia";
    public static final String LEBANON = "lebanon";
    public static final String LAOS = "laos";
    public static final String LESOTHO = "lesotho";
    public static final String LIBERIA = "liberia";
    public static final String LIBYA = "libya";
    public static final String LIECHTENSTEIN = "liechtenstein";
    public static final String LITHUANIA = "lithuania";
    public static final String MACEDONIA = "macedonia";
    public static final String MADAGASCAR = "madagascar";
    public static final String MALAWI = "malawi";
    public static final String MALI = "mali";
    public static final String MALTA = "malta";
    public static final String MALDIVES = "maldives";
    public static final String MARSHALL_ISLANDS = "marshall islands";
    public static final String MARTINIQUE = "martinique";
    public static final String MONTSERRAT = "montserrat";
    public static final String MYANMAR = "myanmar";
    public static final String PACIFIC_ISLANDS = "pacific islands";
    public static final String PALESTINIAN_AUTHORITY = "palestinian authority";
    public static final String REUNION = "reunion";
    public static final String UNION_OF_MYANMAR = "union of myanmar";
    public static final String MOROCCO = "morocco";
    public static final String MAURITANIA = "mauritania";
    public static final String MAURITIUS = "mauritius";
    public static final String MEXICO = "mexico";
    public static final String MOLDOVA = "moldova";
    public static final String MONACO = "monaco";
    public static final String MOZAMBIQUE = "mozambique";
    public static final String NKOREA = "Korea, People's Democratic Rep";
    public static final String NEW_ZEALAND = "new zealand";
    public static final String NEW_CALEDONIA = "new caledonia";
    public static final String NORWAY = "norway";
    public static final String NAMIBIA = "namibia";
    public static final String PAPUA_NEW_GUINEA = "papua new guinea";
    public static final String NICARAGUA = "nicaragua";
    public static final String NIGERIA = "nigeria";
    public static final String OMAN = "oman";
    public static final String POLAND = "poland";
    public static final String PAKISTAN = "pakistan";
    public static final String PANAMA = "panama";
    public static final String PALESTINE = "palestine";
    public static final String PARAGUAY = "paraguay";
    public static final String YEMEN = "yemen";
    public static final String PERU = "peru";
    public static final String PHILIPPINES = "philippines";
    public static final String PORTUGAL = "portugal";
    public static final String PUERTO_RICO = "puerto rico";
    public static final String QATAR = "qatar";
    public static final String USSR = "ussr";
    public static final String SINGAPORE = "singapore";
    public static final String SYRIA = "syria";
    public static final String TURKMENISTAN = "turkmenistan";
    public static final String TAIWAN = "taiwan";
    public static final String RWANDA = "rwanda";
    public static final String UNITED_ARAB_EMIRATES = "united arab emirates";
    public static final String SUDAN = "sudan";
    public static final String TNT = "trinidad and tobago";
    public static final String ZIMBABWE = "zimbabwe";
    public static final String ZAMBIA = "zambia";
    public static final String ZAIRE = "zaire";
    public static final String NEPAL = "nepal";
    public static final String THAILAND = "thailand";
    public static final String TAJIKISTAN = "tajikistan";
    public static final String GERMAN_DEMOCRATIC_REPUBLIC = "german democratic republic";
    public static final String GERMANY_FEDERAL_REPUBLIC = "germany federal republic";
    public static final String MICRONESIA = "micronesia";
    public static final String VENEZUELA = "venezuela";
    public static final String SWAZILAND = "swaziland";
    public static final String UZBEKISTAN = "uzbekistan";
    public static final String UGANDA = "uganda";
    public static final String SLOVAKIA = "slovakia";
    public static final String SENEGAL = "senegal";
    public static final String URUGUAY = "uruguay";
    public static final String SAMOA = "samoa";
    public static final String SLOVENIA = "slovenia";
    public static final String TUNISIA = "tunisia";
    public static final String SAN_MARINO = "san marino";
    public static final String SERBIA = "serbia";
    public static final String SEYCHELLES = "seychelles";
    public static final String SRI_LANKA = "sri lanka";
    public static final String SIERRA_LEONE = "sierra leone";
    public static final String SOUTHERN_RHODESIA = "southern rhodesia";
    public static final String ST_LUCIA = "st. lucia";
    public static final String SOMALIA = "somalia";
    public static final String TOGO = "togo";
    public static final String TONGA = "tonga";
    public static final String VANUATU = "vanuatu";
    public static final String VATICAN_CITY = "vatican city";
    public static final String SURINAME = "suriname";
    public static final String TANZANIA = "tanzania, united republic of";
    public static final String VIET_NAM = "viet nam";
    public static final String MALAYSIA = "malaysia";
    public static final String INTER_ORGANIZATION = "international organizations";
    public static final String AMERICAN_SAMOA = "american samoa";
    public static final String ANGUILLA = "anguilla";
    public static final String SOLOMON_ISLANDS = "solomon islands";
    public static final String COCOS_ISLANDS = "cocos (keeling) islands";
    public static final String CAPE_VERDE = "cape verde";
    public static final String GILBRALTAR = "gilbraltar";
    public static final String BRITISH_TERRITORY = "british indian ocean territory";
    public static final String MACUA = "macua";
    public static final String MOGOLIA = "mogolia";
    public static final String MONTENEGRO = "montenegro";
    public static final String NIUE = "niue";
    public static final String NORFOLK_ISLAND = "norfolk island";
    public static final String NAURU = "nauru";
    public static final String PITCAIRN = "pitcairn";
    public static final String RHODESIA = "rhodesia";
    public static final String ST_HELENA = "st. helena";
    public static final String SVALBARD_JAN_MAYEN_ISLANDS = "svalbard and jan mayen islands";
    public static final String TURKS_AND_CAICOS_ISLANDS = "turks and caicos islands";
    public static final String TOKELAU = "tokelau";
    public static final String SAO_TOME_PRINCIPE = "sao tome and principe";
    public static final String TUVALU = "tuvalu";
    public static final String BURKINA_FASO = "burkina faso";
    public static final String SAINT_VICENT_GRENADINES = "saint vicent & the grenadines";
    public static final String WALLIS_FUTUNA_ISLANDS = "wallis and futuna islands";
    public static final String WESTERN_SAHARA = "western sahara";
    public static final String SAO_TOME_AND_PRINCIPE = "sao tome and principe";

    private static Perl5Util perl = new Perl5Util();
    public static Hashtable<String, String> htCountry = new Hashtable<String, String>();
    static {
        htCountry.put("international organizations", INTER_ORGANIZATION);
        htCountry.put("international organization", INTER_ORGANIZATION);
        htCountry.put("antigua and barbuda", ANTIGUA);
        htCountry.put("antigua & barbuda", ANTIGUA);
        htCountry.put("american samoa", AMERICAN_SAMOA);
        htCountry.put("anguilla", ANGUILLA);
        htCountry.put("solomon islands", SOLOMON_ISLANDS);
        htCountry.put("brunei darussalamy", BRUNEI);
        htCountry.put("cocos (keeling) islands", COCOS_ISLANDS);
        htCountry.put("cape verde", CAPE_VERDE);
        htCountry.put("falkland islands (malvinas)", FALKLAND_ISLANDS);
        htCountry.put("gilbraltar", GILBRALTAR);
        htCountry.put("british indian ocean territory", BRITISH_TERRITORY);
        htCountry.put("united states minor outer isl.", US);
        htCountry.put("iran (islamic republic of)", IRAN);
        htCountry.put("islamic republic of iran", IRAN);
        htCountry.put("laos, people's democratic rep", LAOS);
        htCountry.put("lao people's democratic republic", LAOS);
        htCountry.put("macua", MACUA);
        htCountry.put("mogolia", MOGOLIA);
        htCountry.put("montenegro", MONTENEGRO);
        htCountry.put("niue", NIUE);
        htCountry.put("norfolk island", NORFOLK_ISLAND);
        htCountry.put("nauru", NAURU);
        htCountry.put("pitcairn", PITCAIRN);
        htCountry.put("qutar", QATAR);
        htCountry.put("rhodesia", RHODESIA);
        htCountry.put("st. helena", ST_HELENA);
        htCountry.put("svalbard and jan mayen islands", SVALBARD_JAN_MAYEN_ISLANDS);
        htCountry.put("Svalbard & Jan Mayen Islands", SVALBARD_JAN_MAYEN_ISLANDS);
        htCountry.put("vatican city state (holy see)", VATICAN_CITY);
        htCountry.put("wallis and futuna islands", WALLIS_FUTUNA_ISLANDS);
        htCountry.put("western sahara", WESTERN_SAHARA);
        htCountry.put("taiwan, province of china", TAIWAN);
        htCountry.put("virgin islands (british)", BVI);
        htCountry.put("virgin islands (united states)", BVI);
        htCountry.put("united states virgin islands", BVI);
        htCountry.put("yemen, democratic republic of", YEMEN);
        htCountry.put("yemen, republic of", YEMEN);
        htCountry.put("burkina faso", BURKINA_FASO);
        htCountry.put("korea, people's democratic rep", SKOREA);
        htCountry.put("korea, republic of", SKOREA);
        htCountry.put("saint vicent & the grenadines", SAINT_VICENT_GRENADINES);
        htCountry.put("St. Vincent & the Grenadines", SAINT_VICENT_GRENADINES);
        htCountry.put("sao tome and principe", SAO_TOME_AND_PRINCIPE);
        htCountry.put("tanzania, united republic of", TANZANIA);
        htCountry.put("tokelau", TOKELAU);
        htCountry.put("turks and caicos islands", TURKS_AND_CAICOS_ISLANDS);
        htCountry.put("turks & caicos islands", TURKS_AND_CAICOS_ISLANDS);
        htCountry.put("tuvalu", TUVALU);
        htCountry.put("antigua", ANTIGUA);
        htCountry.put("(india)", INDIA);
        htCountry.put("(sri lanka)", SRI_LANKA);
        htCountry.put("ar", ARMENIA);
        htCountry.put("ay", ANTARCTICA);
        htCountry.put("af", AFGHANISTAN);
        htCountry.put("afghan", AFGHANISTAN);
        htCountry.put("afghanistan", AFGHANISTAN);
        htCountry.put("alaska", US);
        htCountry.put("albania", ALBANIA);
        htCountry.put("albany", US);
        htCountry.put("alberta", CANADA);
        htCountry.put("alger", ALGERIA);
        htCountry.put("algeria", ALGERIA);
        htCountry.put("algerie", ALGERIA);
        htCountry.put("amernia", ARMENIA);
        htCountry.put("andorra", ANDORRA);
        htCountry.put("angola", ANGOLA);
        htCountry.put("antarct", ANTARCTICA);
        htCountry.put("antarctica", ANTARCTICA);
        htCountry.put("arg", ARGENTINA);
        htCountry.put("argen", ARGENTINA);
        htCountry.put("argent", ARGENTINA);
        htCountry.put("argentina", ARGENTINA);
        htCountry.put("armenia", ARMENIA);
        htCountry.put("athens", GREECE);
        htCountry.put("au", AUSTRIA);
        htCountry.put("australia", AUSTRALIA);
        htCountry.put("austria", AUSTRIA);
        htCountry.put("azerb", AZERBAIJAN);
        htCountry.put("azerbaidzhan", AZERBAIJAN);
        htCountry.put("azerbaijan", AZERBAIJAN);
        htCountry.put("azerbaijan republic", AZERBAIJAN);
        htCountry.put("azerbajdzhan", AZERBAIJAN);
        htCountry.put("belg", BELGIUM);
        htCountry.put("bras", BRAZIL);
        htCountry.put("braz", BRAZIL);
        htCountry.put("bssr", BELARUS);
        htCountry.put("bahamas", BAHAMAS);
        htCountry.put("bahama", BAHAMAS);
        htCountry.put("bahrain", BAHRAIN);
        htCountry.put("bahrein", BAHRAIN);
        htCountry.put("bangladesh", BANGLADESH);
        htCountry.put("barbados", BARBADOS);
        htCountry.put("barcelona", SPAIN);
        htCountry.put("begium", BELGIUM);
        htCountry.put("beijing", CHINA);
        htCountry.put("bel", BELGIUM);
        htCountry.put("belarus", BELARUS);
        htCountry.put("belarus'", BELARUS);
        htCountry.put("belgi", BELGIUM);
        htCountry.put("belgique", BELGIUM);
        htCountry.put("belgium", BELGIUM);
        htCountry.put("belize", BELIZE);
        htCountry.put("belorus", BELARUS);
        htCountry.put("belorussia", BELARUS);
        htCountry.put("benin", BENIN);
        htCountry.put("bermuda", BERMUDA);
        htCountry.put("bhutan", BHUTAN);
        htCountry.put("boliv", BOLIVIA);
        htCountry.put("bolivia", BOLIVIA);
        htCountry.put("bologna", ITALY);
        htCountry.put("bombay", INDIA);
        htCountry.put("bosnia", BOSNIA);
        htCountry.put("bosnia and herzegovina", BOSNIA);
        htCountry.put("bosnia and herzegowina", BOSNIA);
        htCountry.put("bosnia-herczegovina", BOSNIA);
        htCountry.put("bosnia-herczegrovna", BOSNIA);
        htCountry.put("bosnia-berzegovina", BOSNIA);
        htCountry.put("bosnia-herz", BOSNIA);
        htCountry.put("botswana", BOTSWANA);
        htCountry.put("bra", BRAZIL);
        htCountry.put("bras", BRAZIL);
        htCountry.put("brasil", BRAZIL);
        htCountry.put("braz", BRAZIL);
        htCountry.put("brazil", BRAZIL);
        htCountry.put("britain", UK);
        htCountry.put("kiribati", KIRIBATI);
        htCountry.put("british virgin islands", BVI);
        htCountry.put("british virgin isls", BVI);
        htCountry.put("brunei", BRUNIE);
        htCountry.put("brunei darussalam", BRUNIE);
        htCountry.put("brussels", BELGIUM);
        htCountry.put("bug", BULGARIA);
        htCountry.put("bul", BULGARIA);
        htCountry.put("bulg", BULGARIA);
        htCountry.put("bulgaria", BULGARIA);
        htCountry.put("bulgarien", BULGARIA);
        htCountry.put("burma", BURMA);
        htCountry.put("burundi", BURUNDI);
        htCountry.put("byelorussia", BELARUS);
        htCountry.put("ca", CANADA);
        htCountry.put("ch", CHINA);
        htCountry.put("co", COLOMBIA);
        htCountry.put("cs", COSTA);
        htCountry.put("cairo", EGYPT);
        htCountry.put("calabria", ITALY);
        htCountry.put("cambodia", CAMBODIA);
        htCountry.put("cameron", CAMEROON);
        htCountry.put("cameroon", CAMEROON);
        htCountry.put("cameroun", CAMEROON);
        htCountry.put("can", CANADA);
        htCountry.put("cancan", CANADA);
        htCountry.put("canada", CANADA);
        htCountry.put("cayman island", CAYMAN);
        htCountry.put("cayman islands", CAYMAN);
        htCountry.put("cent afr repub", CAR);
        htCountry.put("central african republic", CAR);
        htCountry.put("chad", CHAD);
        htCountry.put("chiina", CHINA);
        htCountry.put("chile", CHILE);
        htCountry.put("chin", CHINA);
        htCountry.put("china", CHINA);
        htCountry.put("china;china", CHINA);
        htCountry.put("china;china;china", CHINA);
        htCountry.put("chine", CHINA);
        htCountry.put("chinese", CHINA);
        htCountry.put("chna", CHINA);
        htCountry.put("cina", CHINA);
        htCountry.put("cleveland", US);
        htCountry.put("Cook Islands", COOK_ISLANDS);
        htCountry.put("col", COLOMBIA);
        htCountry.put("colo", COLOMBIA);
        htCountry.put("colom", COLOMBIA);
        htCountry.put("colomb", COLOMBIA);
        htCountry.put("colombia", COLOMBIA);
        htCountry.put("colorado", US);
        htCountry.put("columb", COLOMBIA);
        htCountry.put("columbia", COLOMBIA);
        htCountry.put("con", CONGO);
        htCountry.put("congo", CONGO);
        htCountry.put("costa rica", COSTA);
        htCountry.put("crete", GREECE);
        htCountry.put("croatia", CROATIA);
        htCountry.put("cuba", CUBA);
        htCountry.put("cyprus", CYPRUS);
        htCountry.put("czec", CZECH);
        htCountry.put("czech", CZECH);
        htCountry.put("czech repub", CZECH);
        htCountry.put("czech republic", CZECH);
        htCountry.put("czecho", CZECH);
        htCountry.put("czechos", CZECH);
        htCountry.put("czechosl", CZECH);
        htCountry.put("czechoslovakia", CZECH);
        htCountry.put("czeck", CZECH);
        htCountry.put("czesch", CZECH);
        htCountry.put("den", DENMARK);
        htCountry.put("daenemark", DENMARK);
        htCountry.put("den", DENMARK);
        htCountry.put("denm", DENMARK);
        htCountry.put("denmark", DENMARK);
        htCountry.put("deutschland", GERMAN_DEMOCRATIC_REPUBLIC);
        htCountry.put("domin repub", DOMINICAN);
        htCountry.put("dominica", DOMINICA);
        htCountry.put("dominican republic", DOMINICAN);
        htCountry.put("djibouti", DJIBOUTI);
        htCountry.put("eg", EGYPT);
        htCountry.put("egypt", EGYPT);
        htCountry.put("engl", UK);
        htCountry.put("england", UK);
        htCountry.put("engl", UK);
        htCountry.put("east ger", GERMAN_DEMOCRATIC_REPUBLIC);
        htCountry.put("east ger", GERMAN_DEMOCRATIC_REPUBLIC);
        htCountry.put("east germany", GERMAN_DEMOCRATIC_REPUBLIC);
        htCountry.put("ecuador", ECUADOR);
        htCountry.put("edinburgh", UK);
        htCountry.put("eritrea", ERITREA);
        htCountry.put("el salvador", ELSAL);
        htCountry.put("emgl", UK);
        htCountry.put("eng", UK);
        htCountry.put("engl", UK);
        htCountry.put("engl   ", UK);
        htCountry.put("engl.", UK);
        // htCountry.put("england", UK);
        htCountry.put("engle", UK);
        htCountry.put("enlgh", UK);
        htCountry.put("equatorial guinea", EQUATORIAL_GUINEA);
        htCountry.put("eqypt", EGYPT);
        htCountry.put("espagne", SPAIN);
        htCountry.put("espana", SPAIN);
        htCountry.put("estonia", ESTONIA);
        htCountry.put("ethiop", ETHIOPIA);
        htCountry.put("ethiopia", ETHIOPIA);
        htCountry.put("fin", FINLAND);
        htCountry.put("finl", FINLAND);
        htCountry.put("fl", FINLAND);
        htCountry.put("fr", FRANCE);
        htCountry.put("frg", FRANCE);
        htCountry.put("faroe islands", FAROE_ISLANDS);
        htCountry.put("faeroe islands", FAROE_ISLANDS);
        htCountry.put("falkland islands", FALKLAND_ISLANDS);
        htCountry.put("fed rep ger", GERMANY_FEDERAL_REPUBLIC);
        htCountry.put("federal republic of ger", GERMANY_FEDERAL_REPUBLIC);
        htCountry.put("federal republic of germany", GERMANY_FEDERAL_REPUBLIC);
        htCountry.put("federated states of micronesia", MICRONESIA);
        htCountry.put("micronesia", MICRONESIA);
        htCountry.put("fiji", FIJI);
        htCountry.put("fin", FINLAND);
        htCountry.put("findl", FINLAND);
        htCountry.put("finl", FINLAND);
        htCountry.put("finland", FINLAND);
        htCountry.put("finnl", FINLAND);
        htCountry.put("florida", US);
        htCountry.put("fra", FRANCE);
        htCountry.put("french guiana", FRENCH_GUIANA);
        htCountry.put("framce", FRANCE);
        htCountry.put("france", FRANCE);
        htCountry.put("fuji islands", FIJI);
        htCountry.put("ga", GAMBIA);
        htCountry.put("gb", GABON);
        htCountry.put("gabon", GABON);
        htCountry.put("gambia", GAMBIA);
        htCountry.put("ger", GERMANY);
        htCountry.put("gibraltar", GIBRALTAR);
        htCountry.put("guyana", GUYANA);
        htCountry.put("kampuchea", KAMPUCHEA);
        htCountry.put("germ", GERMANY);
        htCountry.put("german democratic republic", GERMAN_DEMOCRATIC_REPUBLIC);
        htCountry.put("germany", GERMANY);
        htCountry.put("germany, federal republic", GERMANY_FEDERAL_REPUBLIC);
        htCountry.put("ghana", GHANA);
        htCountry.put("guadaloupe", GUADALOUPE);
        htCountry.put("glasgow", UK);
        htCountry.put("grand duchy of luxembourg", LUXEMBOURG);
        htCountry.put("gre", GREECE);
        htCountry.put("greace", GREECE);
        htCountry.put("great britain", UK);
        htCountry.put("grece", GREECE);
        htCountry.put("greece", GREECE);
        htCountry.put("greenland", GREENLAND);
        htCountry.put("grenada", GRENADA);
        htCountry.put("guadeloupe", GUADELOUPE);
        htCountry.put("georgia", GEORGIA);
        htCountry.put("guam", GUAM);
        htCountry.put("guatem", GUATEMALA);
        htCountry.put("guatemala", GUATEMALA);
        htCountry.put("guinea", GUINEA);
        htCountry.put("guinena", GUINEA);
        htCountry.put("hamburg", GERMANY);
        htCountry.put("hawaii", US);
        htCountry.put("haiti", HAITI);
        htCountry.put("hol", NETHERLANDS);
        htCountry.put("holland", NETHERLANDS);
        htCountry.put("honduras", HONDURAS);
        htCountry.put("hong kong", HONG_KONG);
        htCountry.put("hun", HUNGARY);
        htCountry.put("hung", HUNGARY);
        htCountry.put("hungary", HUNGARY);
        htCountry.put("is", ISRAEL);
        htCountry.put("isr", ISRAEL);
        htCountry.put("italy", ITALY);
        htCountry.put("ice", ICELAND);
        htCountry.put("icel", ICELAND);
        htCountry.put("iceland", ICELAND);
        htCountry.put("in", INDIA);
        htCountry.put("ind", INDIA);
        htCountry.put("india", INDIA);
        htCountry.put("india.", INDIA);
        htCountry.put("indiana", US);
        htCountry.put("indone", INDONESIA);
        htCountry.put("indones", INDONESIA);
        htCountry.put("indonesia", INDONESIA);
        htCountry.put("inida", INDIA);
        htCountry.put("iran", IRAN);
        htCountry.put("iraq", IRAQ);
        htCountry.put("ire", IRELAND);
        htCountry.put("irel", IRELAND);
        htCountry.put("ireland", IRELAND);
        htCountry.put("irkutsk", RUSSIA);
        htCountry.put("israel", ISRAEL);
        htCountry.put("isrl", ISRAEL);
        htCountry.put("istanbul, turk", TURKEY);
        htCountry.put("ita", ITALY);
        htCountry.put("ital", ITALY);
        htCountry.put("italia", ITALY);
        htCountry.put("italie", ITALY);
        htCountry.put("ivory coast", IVORY_COAST);
        htCountry.put("c&ocirc;te d'ivoire (ivory coast)", IVORY_COAST);
        htCountry.put("jp", JAPAN);
        htCountry.put("jpn", JAPAN);
        htCountry.put("jam", JAMAICA);
        htCountry.put("jamaica", JAMAICA);
        htCountry.put("jap", JAPAN);
        htCountry.put("japan", JAPAN);
        htCountry.put("japn", JAPAN);
        htCountry.put("jerusalem", ISRAEL);
        htCountry.put("jordan", JORDAN);
        htCountry.put("jordon", JORDAN);
        htCountry.put("jpan", JAPAN);
        htCountry.put("jpnjpn", JAPAN);
        htCountry.put("jugosl", YUGOSLAVIA);
        htCountry.put("jugoslaviya", YUGOSLAVIA);
        htCountry.put("jugoslawien", YUGOSLAVIA);
        htCountry.put("kaz", KAZAKHSTAN);
        htCountry.put("kazakh", KAZAKHSTAN);
        htCountry.put("kazakhastan", KAZAKHSTAN);
        htCountry.put("kazakhstan", KAZAKHSTAN);
        htCountry.put("kazakstan", KAZAKHSTAN);
        htCountry.put("kazan", KAZAKHSTAN);
        htCountry.put("kenya", KENYA);
        htCountry.put("kiev", UKRAINE);
        htCountry.put("kirg", KYRGYZSTAN);
        htCountry.put("kirgizia", KYRGYZSTAN);
        htCountry.put("korea", SKOREA);
        htCountry.put("korea (south)", SKOREA);
        htCountry.put("kuwait", KUWAIT);
        htCountry.put("kyrgyzstan", KYRGYZSTAN);
        htCountry.put("laos", LAOS);
        htCountry.put("lat", LATVIA);
        htCountry.put("latvia", LATVIA);
        htCountry.put("leban", LEBANON);
        htCountry.put("lebanan", LEBANON);
        htCountry.put("lebanon", LEBANON);
        htCountry.put("leningrad", RUSSIA);
        htCountry.put("lesotho", LESOTHO);
        htCountry.put("liberia", LIBERIA);
        htCountry.put("libya", LIBYA);
        htCountry.put("libyan arab jamahiriya", LIBYA);
        htCountry.put("liechstenstein", LIECHTENSTEIN);
        htCountry.put("liechtenstein", LIECHTENSTEIN);
        htCountry.put("lit", LITHUANIA);
        htCountry.put("lith", LITHUANIA);
        htCountry.put("lithuania", LITHUANIA);
        htCountry.put("lithuanian ssr", LITHUANIA);
        htCountry.put("litovskaya respublica", LITHUANIA);
        htCountry.put("lituania", LITHUANIA);
        htCountry.put("london", UK);
        htCountry.put("luxemb", LUXEMBOURG);
        htCountry.put("luxembourg", LUXEMBOURG);
        htCountry.put("luxemburg", LUXEMBOURG);
        htCountry.put("macao", CHINA);
        htCountry.put("macau", CHINA);
        htCountry.put("maced", MACEDONIA);
        htCountry.put("macedonia", MACEDONIA);
        htCountry.put("madagascar", MADAGASCAR);
        htCountry.put("malawi", MALAWI);
        htCountry.put("malay", MALAYSIA);
        htCountry.put("malaya", MALAYSIA);
        htCountry.put("malays", MALAYSIA);
        htCountry.put("malaysi", MALAYSIA);
        htCountry.put("malaysia", MALAYSIA);
        htCountry.put("maldives", MALDIVES);
        htCountry.put("marshall islands", MARSHALL_ISLANDS);
        htCountry.put("martinique", MARTINIQUE);
        htCountry.put("montserrat", MONTSERRAT);
        htCountry.put("myanmar", MYANMAR);
        htCountry.put("netherlands antilles", NETHERLANDS_ANTILLES);
        htCountry.put("mali", MALI);
        htCountry.put("malta", MALTA);
        htCountry.put("manitoba", CANADA);
        htCountry.put("maroc", MOROCCO);
        htCountry.put("marocco", MOROCCO);
        htCountry.put("mauritania", MAURITANIA);
        htCountry.put("mauritius", MAURITIUS);
        htCountry.put("mex", MEXICO);
        htCountry.put("mexi", MEXICO);
        htCountry.put("mexico", MEXICO);
        htCountry.put("minnesota", US);
        htCountry.put("missouri", US);
        htCountry.put("mold", MOLDOVA);
        htCountry.put("moldavia", MOLDOVA);
        htCountry.put("moldova, Republic of", MOLDOVA);
        htCountry.put("moldova", MOLDOVA);
        htCountry.put("monaco", MONACO);
        htCountry.put("mongolia", CHINA);
        htCountry.put("moroc", MOROCCO);
        htCountry.put("morocco", MOROCCO);
        htCountry.put("morrocco", MOROCCO);
        htCountry.put("moscow", RUSSIA);
        htCountry.put("moscow region", RUSSIA);
        htCountry.put("mozambique", MOZAMBIQUE);
        htCountry.put("munich", GERMANY);
        htCountry.put("n korea", NKOREA);
        htCountry.put("n z", NEW_ZEALAND);
        htCountry.put("n zea", NEW_ZEALAND);
        htCountry.put("n zeal", NEW_ZEALAND);
        htCountry.put("n.e. china", CHINA);
        htCountry.put("nc", NEW_CALEDONIA);
        htCountry.put("nj", US);
        htCountry.put("nl", NETHERLANDS);
        htCountry.put("norw", NORWAY);
        htCountry.put("norway", NORWAY);
        htCountry.put("ny", US);
        htCountry.put("nz", NEW_ZEALAND);
        htCountry.put("namibia", NAMIBIA);
        htCountry.put("nepal", NEPAL);
        htCountry.put("neth", NETHERLANDS);
        htCountry.put("neth ", NETHERLANDS);
        htCountry.put("nether", NETHERLANDS);
        htCountry.put("netherl", NETHERLANDS);
        htCountry.put("netherlands", NETHERLANDS);
        htCountry.put("nethl", NETHERLANDS);
        htCountry.put("neths", NETHERLANDS);
        htCountry.put("new caledonia", NEW_CALEDONIA);
        htCountry.put("new guinea", PAPUA_NEW_GUINEA);
        htCountry.put("new jersey", US);
        htCountry.put("new mex", US);
        htCountry.put("new mexico", US);
        htCountry.put("new york", US);
        htCountry.put("new zeal", NEW_ZEALAND);
        htCountry.put("new zealand", NEW_ZEALAND);
        htCountry.put("nicar", NICARAGUA);
        htCountry.put("nicaragua", NICARAGUA);
        htCountry.put("niger", NIGERIA);
        htCountry.put("nigeria", NIGERIA);
        htCountry.put("north korea", NKOREA);
        htCountry.put("odessa", UKRAINE);
        htCountry.put("ohio", US);
        htCountry.put("okinawa", JAPAN);
        htCountry.put("oman", OMAN);
        htCountry.put("oregon", US);
        htCountry.put("orlanda", US);
        htCountry.put("osaka", JAPAN);
        htCountry.put("p. r. china", CHINA);
        htCountry.put("p.r. china", CHINA);
        htCountry.put("p.r.c.", CHINA);
        htCountry.put("pr china", CHINA);
        htCountry.put("pak", PAKISTAN);
        htCountry.put("pakistan", PAKISTAN);
        htCountry.put("palestine", PALESTINE);
        htCountry.put("panama", PANAMA);
        htCountry.put("papau new guinea", PAPUA_NEW_GUINEA);
        htCountry.put("papua new guinea", PAPUA_NEW_GUINEA);
        htCountry.put("parag", PARAGUAY);
        htCountry.put("paraguay", PARAGUAY);
        htCountry.put("peking", CHINA);
        htCountry.put("people's democr repub of yemen", YEMEN);
        htCountry.put("people's republic of china", CHINA);
        htCountry.put("peoples republic of china", CHINA);
        // htCountry.put("peoples republic of china", CHINA);
        htCountry.put("peru", PERU);
        htCountry.put("phil", PHILIPPINES);
        htCountry.put("philip", PHILIPPINES);
        htCountry.put("philipp", PHILIPPINES);
        htCountry.put("philippines", PHILIPPINES);
        htCountry.put("phillipp", PHILIPPINES);
        htCountry.put("pol", POLAND);
        htCountry.put("poland", POLAND);
        htCountry.put("porsgrunn norway", NORWAY);
        htCountry.put("port", PORTUGAL);
        htCountry.put("portl", PORTUGAL);
        htCountry.put("portugal", PORTUGAL);
        htCountry.put("puerto rico", PUERTO_RICO);
        htCountry.put("pacific islands", PACIFIC_ISLANDS);
        htCountry.put("palestinian authority", PALESTINIAN_AUTHORITY);
        htCountry.put("reunion", REUNION);
        htCountry.put("r&eacute;union", REUNION);
        htCountry.put("qatar", QATAR);
        htCountry.put("ro", ROMANIA);
        htCountry.put("russia", RUSSIA);
        htCountry.put("rep. germany", GERMANY);
        htCountry.put("republic of china", CHINA);
        htCountry.put("republic of ger", GERMANY);
        htCountry.put("republic of germany", GERMANY);
        htCountry.put("republic of korea", SKOREA);
        htCountry.put("republic of s afr", SOUTH_AFRICA);
        htCountry.put("republic of south afr", SOUTH_AFRICA);
        htCountry.put("republic of south africa", SOUTH_AFRICA);
        htCountry.put("rissia", RUSSIA);
        htCountry.put("rom", ROMANIA);
        htCountry.put("roma", ROMANIA);
        htCountry.put("romania", ROMANIA);
        htCountry.put("rumania", ROMANIA);
        htCountry.put("rumanien", ROMANIA);
        htCountry.put("rus", RUSSIA);
        htCountry.put("rusia", RUSSIA);
        htCountry.put("russ", RUSSIA);
        htCountry.put("russian", RUSSIA);
        htCountry.put("russian federation", RUSSIA);
        htCountry.put("rwanda", RWANDA);
        htCountry.put("s a", SOUTH_AFRICA);
        htCountry.put("s af", SOUTH_AFRICA);
        htCountry.put("s afr", SOUTH_AFRICA);
        htCountry.put("s afri", SOUTH_AFRICA);
        htCountry.put("s africa", SOUTH_AFRICA);
        htCountry.put("s arabia", SAUDI_ARABIA);
        htCountry.put("s korea", SKOREA);
        htCountry.put("s. afr", SOUTH_AFRICA);
        htCountry.put("s. africa", SOUTH_AFRICA);
        htCountry.put("s. korea", SKOREA);
        htCountry.put("s.afr", SOUTH_AFRICA);
        htCountry.put("sa", SAUDI_ARABIA);
        htCountry.put("se", SEYCHELLES);
        htCountry.put("sf", SOUTH_AFRICA);
        htCountry.put("south korea", SKOREA);
        htCountry.put("spain", SPAIN);
        htCountry.put("ssr", USSR);
        htCountry.put("swed", SWEDEN);
        htCountry.put("switz", SWITZERLAND);
        htCountry.put("samoa", SAMOA);
        htCountry.put("san marino", SAN_MARINO);
        htCountry.put("saskatchewan", CANADA);
        htCountry.put("saudi", SAUDI_ARABIA);
        htCountry.put("saudi arabi", SAUDI_ARABIA);
        htCountry.put("saudi arabia", SAUDI_ARABIA);
        htCountry.put("saudi arbia", SAUDI_ARABIA);
        htCountry.put("saudi arubia", SAUDI_ARABIA);
        htCountry.put("saudi-arabia", SAUDI_ARABIA);
        htCountry.put("saudia arabia", SAUDI_ARABIA);
        htCountry.put("sauid arabia", SAUDI_ARABIA);
        htCountry.put("sauidi arabia", SAUDI_ARABIA);
        htCountry.put("scolt", UK);
        htCountry.put("scot", UK);
        htCountry.put("scotl", UK);
        htCountry.put("scotl  ", UK);
        htCountry.put("scotlusa", UK);
        htCountry.put("scotland", UK);
        htCountry.put("scott", UK);
        htCountry.put("sctl", UK);
        htCountry.put("senegal", SENEGAL);
        htCountry.put("seoul", SKOREA);
        htCountry.put("serbia", SERBIA);
        htCountry.put("serbia and montenegro", SERBIA);
        htCountry.put("seychelles", SEYCHELLES);
        htCountry.put("sf", SOUTH_AFRICA);
        htCountry.put("siberia", RUSSIA);
        htCountry.put("sierra leone", SIERRA_LEONE);
        htCountry.put("sing", SINGAPORE);
        htCountry.put("singaphore", SINGAPORE);
        htCountry.put("singapore", SINGAPORE);
        htCountry.put("singapore 0511", SINGAPORE);
        htCountry.put("singpore", SINGAPORE);
        htCountry.put("sir lanka", SRI_LANKA);
        htCountry.put("sri lanka", SRI_LANKA);
        htCountry.put("slovak", SLOVAKIA);
        htCountry.put("slovak republic", SLOVAKIA);
        htCountry.put("slovakia", SLOVAKIA);
        htCountry.put("slovakiya", SLOVAKIA);
        htCountry.put("slovenia", SLOVENIA);
        htCountry.put("slovenija", SLOVENIA);
        htCountry.put("somalia", SOMALIA);
        htCountry.put("south af", SOUTH_AFRICA);
        htCountry.put("south afr", SOUTH_AFRICA);
        htCountry.put("south afri", SOUTH_AFRICA);
        htCountry.put("south africa", SOUTH_AFRICA);
        htCountry.put("southern rhodesia", SOUTHERN_RHODESIA);
        htCountry.put("st. lucia", ST_LUCIA);
        htCountry.put("saint lucia", ST_LUCIA);
        htCountry.put("sp", SPAIN);
        htCountry.put("spn", SPAIN);
        htCountry.put("state of bahrain", BAHRAIN);
        htCountry.put("state of qatar", QATAR);
        htCountry.put("sudan", SUDAN);
        htCountry.put("sultanate of oman", OMAN);
        htCountry.put("suriname", SURINAME);
        htCountry.put("swazil", SWAZILAND);
        htCountry.put("swaziland", SWAZILAND);
        htCountry.put("swe", SWEDEN);
        htCountry.put("swed", SWEDEN);
        htCountry.put("swedswed", SWEDEN);
        htCountry.put("sweden", SWEDEN);
        htCountry.put("swedish", SWEDEN);
        htCountry.put("swez", SWITZERLAND);
        htCountry.put("swit", SWITZERLAND);
        htCountry.put("switz", SWITZERLAND);
        htCountry.put("switzer", SWITZERLAND);
        htCountry.put("switzerl", SWITZERLAND);
        htCountry.put("switzerland", SWITZERLAND);
        htCountry.put("switzl", SWITZERLAND);
        htCountry.put("sydney", AUSTRALIA);
        htCountry.put("syria", SYRIA);
        htCountry.put("syrian arab republic", SYRIA);
        htCountry.put("turk", TURKEY);
        htCountry.put("tx", TURKMENISTAN);
        htCountry.put("turkmenistan", TURKMENISTAN);
        htCountry.put("togo", TOGO);
        htCountry.put("tonga", TONGA);
        htCountry.put("taiw", TAIWAN);
        htCountry.put("taiwain", TAIWAN);
        htCountry.put("taiwan", TAIWAN);
        htCountry.put("tajikistan", TAJIKISTAN);
        htCountry.put("tanzan", TANZANIA);
        htCountry.put("tanzania", TANZANIA);
        htCountry.put("tawain", TAIWAN);
        htCountry.put("th", THAILAND);
        htCountry.put("thail", THAILAND);
        htCountry.put("thailand", THAILAND);
        htCountry.put("the neth", NETHERLANDS);
        htCountry.put("the netherlands", NETHERLANDS);
        htCountry.put("thial", THAILAND);
        htCountry.put("tiawan", TAIWAN);
        htCountry.put("tokyo", JAPAN);
        htCountry.put("trinidad", TNT);
        htCountry.put("trinidad & tobago", TNT);
        htCountry.put("trinidad &amp; tobago", TNT);
        htCountry.put("trinidad (w.i.)", TNT);
        htCountry.put("trinidad and tobago", TNT);
        htCountry.put("tunis", TUNISIA);
        htCountry.put("tunisia", TUNISIA);
        htCountry.put("tunisie", TUNISIA);
        htCountry.put("turk", TURKEY);
        htCountry.put("turkey", TURKEY);
        htCountry.put("u.k.", UK);
        htCountry.put("u.s.a.", US);
        htCountry.put("u.s.s.r.", USSR);
        htCountry.put("ukr ssr", UKRAINE);
        htCountry.put("urss", USSR);
        htCountry.put("usa", US);
        htCountry.put("usa0704", US);
        htCountry.put("usausa", US);
        htCountry.put("ussr", USSR);
        htCountry.put("ussr acad of sciences", USSR);
        htCountry.put("usa", US);
        htCountry.put("uganda", UGANDA);
        htCountry.put("uk", UK);
        htCountry.put("ukaine", UKRAINE);
        htCountry.put("ukr", UKRAINE);
        htCountry.put("ukrssr", UKRAINE);
        htCountry.put("ukraine", UKRAINE);
        htCountry.put("ukrainian ssr", UKRAINE);
        htCountry.put("unite arab emirates", UNITED_ARAB_EMIRATES);
        htCountry.put("united arab emirate", UNITED_ARAB_EMIRATES);
        htCountry.put("united arab emirates", UNITED_ARAB_EMIRATES);
        htCountry.put("united arabs emirates", UNITED_ARAB_EMIRATES);
        htCountry.put("united kingdom", UK);
        htCountry.put("united kingdom (great britain)", UK);
        htCountry.put("united states", US);
        htCountry.put("united states of america", US);
        htCountry.put("united states minor outlying islands", US);
        htCountry.put("urug", URUGUAY);
        htCountry.put("uruguay", URUGUAY);
        htCountry.put("uzb", UZBEKISTAN);
        htCountry.put("uzbekhistan", UZBEKISTAN);
        htCountry.put("uzbekistan", UZBEKISTAN);
        htCountry.put("union of myanmar", UNION_OF_MYANMAR);
        htCountry.put("vanuatu", VANUATU);
        htCountry.put("vatican city", VATICAN_CITY);
        htCountry.put("ven", VENEZUELA);
        htCountry.put("vene'z", VENEZUELA);
        htCountry.put("venez", VENEZUELA);
        htCountry.put("venezuela", VENEZUELA);
        htCountry.put("venz", VENEZUELA);
        htCountry.put("vienna", AUSTRIA);
        htCountry.put("viet", VIET_NAM);
        htCountry.put("viet nam", VIET_NAM);
        htCountry.put("vietnam", VIET_NAM);
        htCountry.put("virginia", US);
        htCountry.put("vitnam", VIET_NAM);
        htCountry.put("w ger", GERMANY);
        htCountry.put("w-ger", GERMANY);
        htCountry.put("w. ger", GERMANY);
        htCountry.put("w. germany", GERMANY);
        htCountry.put("wales", UK);
        htCountry.put("wast ger", GERMANY);
        htCountry.put("west australia", AUSTRALIA);
        htCountry.put("west ger", GERMANY);
        htCountry.put("west ger.", GERMANY);
        htCountry.put("west gerwest ger", GERMANY);
        htCountry.put("west germ", GERMANY);
        htCountry.put("west germany", GERMANY);
        htCountry.put("west-ger", GERMANY);
        htCountry.put("western aust", AUSTRALIA);
        htCountry.put("western australia", AUSTRALIA);
        htCountry.put("wet ger", GERMANY);
        htCountry.put("yemen", YEMEN);
        htCountry.put("yemen arab repub", YEMEN);
        htCountry.put("yemen arab republic", YEMEN);
        htCountry.put("ygosl", YUGOSLAVIA);
        htCountry.put("yogosl", YUGOSLAVIA);
        htCountry.put("yogusl", YUGOSLAVIA);
        htCountry.put("yug", YUGOSLAVIA);
        htCountry.put("yugasl", YUGOSLAVIA);
        htCountry.put("yugo", YUGOSLAVIA);
        htCountry.put("yugol", YUGOSLAVIA);
        htCountry.put("yugos", YUGOSLAVIA);
        htCountry.put("yugosl", YUGOSLAVIA);
        htCountry.put("yugoslyugosl", YUGOSLAVIA);
        htCountry.put("yugoslavia", YUGOSLAVIA);
        htCountry.put("yugsl", YUGOSLAVIA);
        htCountry.put("yugsol", YUGOSLAVIA);
        htCountry.put("yukon", US);
        htCountry.put("yvgosl", YUGOSLAVIA);
        htCountry.put("zaire", ZAIRE);
        htCountry.put("zambia", ZAMBIA);
        htCountry.put("zimbabwe", ZIMBABWE);
        htCountry.put("zimbabwee", ZIMBABWE);
        htCountry.put("zuerich", SWITZERLAND);
        htCountry.put("zurich", SWITZERLAND);
        htCountry.put("audi arabia", SAUDI_ARABIA);

        htCountry.put("birmingham, england", UK);
        htCountry.put("czechslovakia", CZECH);
        htCountry.put("paris", FRANCE);
        htCountry.put("republic dem du congo", CONGO);
        htCountry.put("roumania", ROMANIA);
        htCountry.put("south australia", AUSTRALIA);
        htCountry.put("soviet union", RUSSIA);
        htCountry.put("cssr", RUSSIA);
        htCountry.put("u. s. a.", US);
        htCountry.put("united states;united states", US);
        htCountry.put("unites states", US);
        htCountry.put("w germany", GERMANY);
        htCountry.put("w.germany", GERMANY);
        htCountry.put("uar", EGYPT);

        // Univnetio Assignee Countries
        htCountry.put("ad", "andorra");
        htCountry.put("ae", "united arab emirates");
        htCountry.put("af", "afghanistan");
        htCountry.put("ag", "antigua");
        htCountry.put("ai", "anguilla");
        htCountry.put("al", "albania");
        htCountry.put("am", "armenia");
        htCountry.put("an", "netherlands");
        htCountry.put("ao", "angola");
        htCountry.put("ap", "aripo");
        htCountry.put("aq", "antarctica");
        htCountry.put("ar", "argentina");
        htCountry.put("as", "american samoa");
        htCountry.put("at", "austria");
        htCountry.put("au", "australia");
        htCountry.put("aw", "aruba");
        htCountry.put("az", "azerbaijan");
        htCountry.put("ba", "bosnia and herzegovina");
        htCountry.put("bb", "barbados");
        htCountry.put("bd", "bangladesh");
        htCountry.put("be", "belgium");
        htCountry.put("bf", "burkina faso");
        htCountry.put("bg", "bulgaria");
        htCountry.put("bh", "bahrain");
        htCountry.put("bi", "burundi");
        htCountry.put("bj", "benin");
        htCountry.put("bm", "bermuda");
        htCountry.put("bn", "brunie");
        htCountry.put("bo", "bolivia");
        htCountry.put("br", "brazil");
        htCountry.put("bs", "bahamas");
        htCountry.put("bt", "bhutan");
        htCountry.put("bu", "burma");
        htCountry.put("bv", "bouvet island");
        htCountry.put("bw", "botswana");
        htCountry.put("by", "belarus");
        htCountry.put("bz", "belize");
        htCountry.put("ca", "canada");
        htCountry.put("cc", "cocos (keeling) islands");
        htCountry.put("cf", "central african republic");
        htCountry.put("cg", "congo");
        htCountry.put("ch", "switzerland");
        htCountry.put("ci", "ivory coast");
        htCountry.put("ck", "cook islands");
        htCountry.put("cl", "chile");
        htCountry.put("cm", "cameroon");
        htCountry.put("cn", "china");
        htCountry.put("co", "colombia");
        htCountry.put("cr", "costa rica");
        htCountry.put("cs", "czechoslovakia");
        htCountry.put("cu", "cuba");
        htCountry.put("cv", "cape verde");
        htCountry.put("cx", "christmas island");
        htCountry.put("cy", "cyprus");
        htCountry.put("cz", "czech republic");
        htCountry.put("dd", "german democratic republic");
        htCountry.put("de", "germany");
        htCountry.put("dj", "djibouti");
        htCountry.put("dk", "denmark");
        htCountry.put("dm", "dominica");
        htCountry.put("do", "dominican republic");
        htCountry.put("dz", "algeria");
        htCountry.put("ea", "eurasian patent office");
        htCountry.put("ec", "ecuador");
        htCountry.put("ee", "estonia");
        htCountry.put("eg", "egypt");
        htCountry.put("eh", "western sahara");
        htCountry.put("ep", "european patent office");
        htCountry.put("er", "eritrea");
        htCountry.put("es", "spain");
        htCountry.put("et", "ethiopia");
        htCountry.put("fi", "finland");
        htCountry.put("fj", "fiji");
        htCountry.put("fk", "falkland islands");
        htCountry.put("fm", "micronesia");
        htCountry.put("fo", "faroe islands");
        htCountry.put("fr", "france");
        htCountry.put("fx", "france, metropolitan");
        htCountry.put("ga", "gabon");
        htCountry.put("gb", "united kingdom");
        htCountry.put("gc", "gulf cooperation council");
        htCountry.put("gd", "grenada");
        htCountry.put("ge", "georgia");
        htCountry.put("gf", "french guiana");
        htCountry.put("gh", "ghana");
        htCountry.put("gi", "gibraltar");
        htCountry.put("gl", "greenland");
        htCountry.put("gm", "gambia");
        htCountry.put("gn", "guinea");
        htCountry.put("gp", "guadaloupe");
        htCountry.put("gq", "equatorial guinea");
        htCountry.put("gr", "greece");
        htCountry.put("gs", "south georgia and the south sandwich islands");
        htCountry.put("gt", "guatemala");
        htCountry.put("gu", "guam");
        htCountry.put("gw", "guinea-bissau");
        htCountry.put("gy", "guyana");
        htCountry.put("hk", "hong kong");
        htCountry.put("hm", "heard & mcDonald islands");
        htCountry.put("hn", "honduras");
        htCountry.put("hr", "croatia");
        htCountry.put("ht", "haiti");
        htCountry.put("hu", "hungary");
        htCountry.put("id", "indonesia");
        htCountry.put("ie", "ireland");
        htCountry.put("il", "israel");
        htCountry.put("in", "india");
        htCountry.put("io", "british indian ocean territory");
        htCountry.put("iq", "iraq");
        htCountry.put("ir", "iran");
        htCountry.put("is", "iceland");
        htCountry.put("it", "italy");
        htCountry.put("jm", "jamaica");
        htCountry.put("ja", "jamaica");
        htCountry.put("jo", "jordan");
        htCountry.put("jp", "japan");
        htCountry.put("ke", "kenya");
        htCountry.put("kg", "kyrgyzstan");
        htCountry.put("kh", "cambodia");
        htCountry.put("ki", "kiribati");
        htCountry.put("km", "comoros");
        htCountry.put("kn", "st. kitts and nevis");
        htCountry.put("kp", "korea, republic of");
        htCountry.put("kr", "korea, republic of");
        htCountry.put("kw", "kuwait");
        htCountry.put("ky", "cayman islands");
        htCountry.put("kz", "kazakhstan");
        htCountry.put("la", "laos");
        htCountry.put("lb", "lebanon");
        htCountry.put("lc", "saint lucia");
        htCountry.put("li", "liechtenstein");
        htCountry.put("lk", "sri lanka");
        htCountry.put("lr", "liberia");
        htCountry.put("ls", "lesotho");
        htCountry.put("lt", "lithuania");
        htCountry.put("lu", "luxembourg");
        htCountry.put("lv", "latvia");
        htCountry.put("ly", "libya");
        htCountry.put("ma", "morocco");
        htCountry.put("mc", "monaco");
        htCountry.put("md", "moldova");
        htCountry.put("mg", "madagascar");
        htCountry.put("mh", "marshall islands");
        htCountry.put("ml", "mali");
        htCountry.put("mm", "myanmar");
        htCountry.put("mn", "mogolia");
        htCountry.put("mo", "china");
        htCountry.put("mp", "northern mariana islands");
        htCountry.put("mq", "martinique");
        htCountry.put("mr", "mauritania");
        htCountry.put("ms", "monserrat");
        htCountry.put("mt", "malta");
        htCountry.put("mu", "mauritius");
        htCountry.put("mv", "maldives");
        htCountry.put("mw", "malawi");
        htCountry.put("mx", "mexico");
        htCountry.put("my", "malaysia");
        htCountry.put("mz", "mozambique");
        htCountry.put("na", "namibia");
        htCountry.put("nc", "new caledonia");
        htCountry.put("ne", "nigeria");
        htCountry.put("nf", "norfolk island");
        htCountry.put("ng", "nigeria");
        htCountry.put("ni", "nicaragua");
        htCountry.put("nl", "netherlands");
        htCountry.put("no", "norway");
        htCountry.put("np", "nepal");
        htCountry.put("nr", "nauru");
        htCountry.put("nt", "neutral zone");
        htCountry.put("nu", "niue");
        htCountry.put("nz", "new zealand");
        htCountry.put("oa", "oapi");
        htCountry.put("om", "oman");
        htCountry.put("pa", "panama");
        htCountry.put("pe", "peru");
        htCountry.put("pf", "french polynesia");
        htCountry.put("pg", "papua new guinea");
        htCountry.put("ph", "philippines");
        htCountry.put("pk", "pakistan");
        htCountry.put("pl", "poland");
        htCountry.put("pm", "st. pierre & miquelon");
        htCountry.put("pn", "pitcairn");
        htCountry.put("pr", "puerto rico");
        htCountry.put("pt", "portugal");
        htCountry.put("pw", "Palau");
        htCountry.put("py", "paraguay");
        htCountry.put("qa", "qatar");
        htCountry.put("re", "reunion");
        htCountry.put("ro", "romania");
        htCountry.put("ru", "russia");
        htCountry.put("rw", "rwanda");
        htCountry.put("sa", "saudi arabia");
        htCountry.put("sb", "solomon islands");
        htCountry.put("sc", "seychelles");
        htCountry.put("sd", "sudan");
        htCountry.put("se", "sweden");
        htCountry.put("sg", "singapore");
        htCountry.put("sh", "st. helena");
        htCountry.put("si", "slovenia");
        htCountry.put("sj", "svalbard and jan mayen islands");
        htCountry.put("sk", "slovakia");
        htCountry.put("sl", "sierra leone");
        htCountry.put("sm", "san marino");
        htCountry.put("sn", "senegal");
        htCountry.put("so", "somalia");
        htCountry.put("sr", "suriname");
        htCountry.put("st", "sao tome and principe");
        htCountry.put("su", "russia");
        htCountry.put("sv", "el salvador");
        htCountry.put("sy", "syria");
        htCountry.put("sz", "swaziland");
        htCountry.put("tc", "turks and caicos islands");
        htCountry.put("td", "chad");
        htCountry.put("tf", "french southern territories");
        htCountry.put("tg", "togo");
        htCountry.put("th", "thailand");
        htCountry.put("tj", "tajikistan");
        htCountry.put("tk", "tokelau");
        htCountry.put("tm", "turkmenistan");
        htCountry.put("tn", "tunisia");
        htCountry.put("to", "tonga");
        htCountry.put("tp", "east timor");
        htCountry.put("tr", "turkey");
        htCountry.put("tt", "trinidad and tobago");
        htCountry.put("tv", "tuvalu");
        htCountry.put("tw", "taiwan");
        htCountry.put("tz", "tanzania, united republic of");
        htCountry.put("ua", "ukraine");
        htCountry.put("ug", "uganda");
        htCountry.put("um", "united states");
        htCountry.put("us", "united states");
        htCountry.put("uy", "uruguay");
        htCountry.put("uz", "uzbekistan");
        htCountry.put("va", "vatican city");
        htCountry.put("vc", "saint vicent & the grenadines");
        htCountry.put("ve", "venezuela");
        htCountry.put("vg", "british virgin islands");
        htCountry.put("vi", "united states virgin islands");
        htCountry.put("vn", "viet nam");
        htCountry.put("vu", "vanuatu");
        htCountry.put("wf", "wallis and futuna islands");
        htCountry.put("wo", "wipo");
        htCountry.put("ws", "samoa");
        htCountry.put("yd", "yemen");
        htCountry.put("ye", "yemen");
        htCountry.put("yt", "mayotte");
        htCountry.put("yu", "yugoslavia");
        htCountry.put("za", "south africa");
        htCountry.put("zm", "zambia");
        htCountry.put("zr", "zaire");
        htCountry.put("zw", "zimbabwe");

        // valid country codes defined in OPSBANK
        htCountry.put("and", "andorra");
        htCountry.put("are", "united arab emirates");
        htCountry.put("afg", "afghanistan");
        htCountry.put("atg", "antigua");
        htCountry.put("aia", "anguilla");
        htCountry.put("alb", "albania");
        htCountry.put("arm", "armenia");
        htCountry.put("nld", "netherlands");
        htCountry.put("ago", "angola");
        htCountry.put("ap", "aripo");
        htCountry.put("ata", "antarctica");
        htCountry.put("arg", "argentina");
        htCountry.put("asm", "american samoa");
        htCountry.put("aut", "austria");
        htCountry.put("aus", "australia");
        htCountry.put("abw", "aruba");
        htCountry.put("aze", "azerbaijan");
        htCountry.put("bih", "bosnia and herzegovina");
        htCountry.put("brb", "barbados");
        htCountry.put("bgd", "bangladesh");
        htCountry.put("bel", "belgium");
        htCountry.put("bfa", "burkina faso");
        htCountry.put("bgr", "bulgaria");
        htCountry.put("bhr", "bahrain");
        htCountry.put("bdi", "burundi");
        htCountry.put("ben", "benin");
        htCountry.put("bmu", "bermuda");
        htCountry.put("brn", "brunie");
        htCountry.put("bol", "bolivia");
        htCountry.put("bra", "brazil");
        htCountry.put("bhs", "bahamas");
        htCountry.put("btn", "bhutan");
        htCountry.put("bu", "burma");
        htCountry.put("bvt", "bouvet island");
        htCountry.put("bwa", "botswana");
        htCountry.put("blr", "belarus");
        htCountry.put("blz", "belize");
        htCountry.put("can", "canada");
        htCountry.put("cck", "cocos (keeling) islands");
        htCountry.put("caf", "central african republic");
        htCountry.put("cog", "congo");
        htCountry.put("che", "switzerland");
        htCountry.put("ci", "ivory coast");
        htCountry.put("cok", "cook islands");
        htCountry.put("chl", "chile");
        htCountry.put("cmr", "cameroon");
        htCountry.put("chn", "china");
        htCountry.put("col", "colombia");
        htCountry.put("cri", "costa rica");
        // htCountry.put("cze", "czechoslovakia");
        htCountry.put("cub", "cuba");
        htCountry.put("cpv", "cape verde");
        htCountry.put("cxr", "christmas island");
        htCountry.put("cyp", "cyprus");
        htCountry.put("cze", "czech republic");
        // htCountry.put("dd", "german democratic republic");
        htCountry.put("deu", "germany");
        htCountry.put("dji", "djibouti");
        htCountry.put("dnk", "denmark");
        htCountry.put("dma", "dominica");
        htCountry.put("dom", "dominican republic");
        htCountry.put("dza", "algeria");
        // htCountry.put("ea", "eurasian patent office");
        htCountry.put("ecu", "ecuador");
        htCountry.put("est", "estonia");
        htCountry.put("egy", "egypt");
        htCountry.put("esh", "western sahara");
        // htCountry.put("ep", "european patent office");
        htCountry.put("eri", "eritrea");
        htCountry.put("esp", "spain");
        htCountry.put("eth", "ethiopia");
        htCountry.put("fin", "finland");
        htCountry.put("fji", "fiji");
        htCountry.put("flk", "falkland islands");
        htCountry.put("fsm", "micronesia");
        htCountry.put("fro", "faroe islands");
        htCountry.put("fra", "france");
        // htCountry.put("fx", "france, metropolitan");
        htCountry.put("gab", "gabon");
        htCountry.put("gbr", "united kingdom");
        // htCountry.put("gc", "gulf cooperation council");
        htCountry.put("grd", "grenada");
        htCountry.put("geo", "georgia");
        htCountry.put("guf", "french guiana");
        htCountry.put("gha", "ghana");
        htCountry.put("gib", "gibraltar");
        htCountry.put("grl", "greenland");
        htCountry.put("gmb", "gambia");
        htCountry.put("gin", "guinea");
        htCountry.put("glp", "guadaloupe");
        htCountry.put("gnq", "equatorial guinea");
        htCountry.put("grc", "greece");
        htCountry.put("ggs", "south georgia and the south sandwich islands");
        htCountry.put("gtm", "guatemala");
        htCountry.put("gum", "guam");
        htCountry.put("gnb", "guinea-bissau");
        htCountry.put("guy", "guyana");
        htCountry.put("hkg", "hong kong");
        htCountry.put("hmd", "heard & mcDonald islands");
        htCountry.put("hnd", "honduras");
        htCountry.put("hrv", "croatia");
        htCountry.put("hti", "haiti");
        htCountry.put("hun", "hungary");
        htCountry.put("idn", "indonesia");
        htCountry.put("irl", "ireland");
        htCountry.put("isr", "israel");
        htCountry.put("ind", "india");
        htCountry.put("iot", "british indian ocean territory");
        htCountry.put("iqq", "iraq");
        htCountry.put("irn", "iran");
        htCountry.put("isl", "iceland");
        htCountry.put("ita", "italy");
        htCountry.put("jam", "jamaica");
        // htCountry.put("ja", "jamaica");
        htCountry.put("jor", "jordan");
        htCountry.put("jpn", "japan");
        htCountry.put("ken", "kenya");
        htCountry.put("kgz", "kyrgyzstan");
        htCountry.put("khm", "cambodia");
        htCountry.put("kir", "kiribati");
        htCountry.put("com", "comoros");
        htCountry.put("kna", "st. kitts and nevis");
        // htCountry.put("kp", "korea, republic of");
        htCountry.put("kor", "korea, republic of");
        htCountry.put("kwt", "kuwait");
        htCountry.put("cym", "cayman islands");
        htCountry.put("kaz", "kazakhstan");
        htCountry.put("lao", "laos");
        htCountry.put("lbn", "lebanon");
        htCountry.put("lca", "saint lucia");
        htCountry.put("lie", "liechtenstein");
        htCountry.put("lka", "sri lanka");
        htCountry.put("lbr", "liberia");
        htCountry.put("lso", "lesotho");
        htCountry.put("ltu", "lithuania");
        htCountry.put("lux", "luxembourg");
        htCountry.put("lva", "latvia");
        htCountry.put("lby", "libya");
        htCountry.put("mar", "morocco");
        htCountry.put("mco", "monaco");
        htCountry.put("mda", "moldova");
        htCountry.put("mdg", "madagascar");
        htCountry.put("mhl", "marshall islands");
        htCountry.put("mli", "mali");
        htCountry.put("mmr", "myanmar");
        htCountry.put("mng", "mogolia");
        // htCountry.put("mo", "china");
        htCountry.put("mnp", "northern mariana islands");
        htCountry.put("mtq", "martinique");
        htCountry.put("mrt", "mauritania");
        htCountry.put("msr", "monserrat");
        htCountry.put("mlt", "malta");
        htCountry.put("mus", "mauritius");
        htCountry.put("mdv", "maldives");
        htCountry.put("mwi", "malawi");
        htCountry.put("mex", "mexico");
        htCountry.put("mys", "malaysia");
        htCountry.put("moz", "mozambique");
        htCountry.put("nam", "namibia");
        htCountry.put("ncl", "new caledonia");
        htCountry.put("nga", "nigeria");
        htCountry.put("nfk", "norfolk island");
        htCountry.put("nga", "nigeria");
        htCountry.put("nic", "nicaragua");
        htCountry.put("nld", "netherlands");
        htCountry.put("nor", "norway");
        htCountry.put("npl", "nepal");
        htCountry.put("nru", "nauru");
        // htCountry.put("nt", "neutral zone");
        htCountry.put("niu", "niue");
        htCountry.put("nzl", "new zealand");
        // htCountry.put("oa", "oapi");
        htCountry.put("omn", "oman");
        htCountry.put("pan", "panama");
        htCountry.put("per", "peru");
        htCountry.put("pyf", "french polynesia");
        htCountry.put("png", "papua new guinea");
        htCountry.put("phl", "philippines");
        htCountry.put("pak", "pakistan");
        htCountry.put("pol", "poland");
        htCountry.put("spm", "st. pierre & miquelon");
        htCountry.put("pcn", "pitcairn");
        htCountry.put("pri", "puerto rico");
        htCountry.put("prt", "portugal");
        htCountry.put("plw", "Palau");
        htCountry.put("pry", "paraguay");
        htCountry.put("qat", "qatar");
        htCountry.put("reu", "reunion");
        htCountry.put("rou", "romania");
        htCountry.put("rus", "russia");
        htCountry.put("rwa", "rwanda");
        htCountry.put("sau", "saudi arabia");
        htCountry.put("slb", "solomon islands");
        htCountry.put("syc", "seychelles");
        htCountry.put("sdn", "sudan");
        htCountry.put("swe", "sweden");
        htCountry.put("sgp", "singapore");
        htCountry.put("sh", "st. helena");
        htCountry.put("svn", "slovenia");
        htCountry.put("sjm", "svalbard and jan mayen islands");
        htCountry.put("svk", "slovakia");
        htCountry.put("sle", "sierra leone");
        htCountry.put("smr", "san marino");
        htCountry.put("sen", "senegal");
        htCountry.put("som", "somalia");
        htCountry.put("sur", "suriname");
        htCountry.put("stp", "sao tome and principe");
        // htCountry.put("su", "russia");
        htCountry.put("slv", "el salvador");
        htCountry.put("syr", "syria");
        htCountry.put("swz", "swaziland");
        htCountry.put("tca", "turks and caicos islands");
        htCountry.put("tcd", "chad");
        htCountry.put("atf", "french southern territories");
        htCountry.put("tgo", "togo");
        htCountry.put("tha", "thailand");
        htCountry.put("tjk", "tajikistan");
        htCountry.put("tkl", "tokelau");
        htCountry.put("tkm", "turkmenistan");
        htCountry.put("tun", "tunisia");
        htCountry.put("ton", "tonga");
        // htCountry.put("tp", "east timor");
        htCountry.put("tur", "turkey");
        htCountry.put("tto", "trinidad and tobago");
        htCountry.put("tuv", "tuvalu");
        htCountry.put("twn", "taiwan");
        htCountry.put("tza", "tanzania, united republic of");
        htCountry.put("ukr", "ukraine");
        htCountry.put("uga", "uganda");
        htCountry.put("usa", "united states");
        // htCountry.put("us", "united states");
        htCountry.put("ury", "uruguay");
        htCountry.put("uzb", "uzbekistan");
        // htCountry.put("va", "vatican city");
        htCountry.put("vct", "saint vicent & the grenadines");
        htCountry.put("ven", "venezuela");
        htCountry.put("vgb", "british virgin islands");
        htCountry.put("vir", "united states virgin islands");
        htCountry.put("vnm", "viet nam");
        htCountry.put("vut", "vanuatu");
        htCountry.put("wlf", "wallis and futuna islands");
        // htCountry.put("wo", "wipo");
        htCountry.put("wsm", "samoa");
        // htCountry.put("yd", "yemen");
        htCountry.put("yem", "yemen");
        htCountry.put("myt", "mayotte");
        // htCountry.put("yu", "yugoslavia");
        htCountry.put("zaf", "south africa");
        htCountry.put("zmb", "zambia");
        // htCountry.put("zr", "zaire");
        htCountry.put("zwe", "zimbabwe");

    }

    public static String getCountry(String af) {

        Enumeration<String> en = htCountry.keys();
        while (en.hasMoreElements()) {
            String next = (String) en.nextElement();
            if (perl.match("/,\\s*" + next + "$/i", af.trim())) {
                String s = (String) htCountry.get(next);
                if (s.trim().length() > 0) {
                    return s;
                } else {
                    return null;
                }
            }

        }

        return null;
    }

    public static String formatCountry(String country) {
        if ((country == null) || (country.trim().equals(""))) {
            return null;
        }

        String coformatted = null;

        country = country.toLowerCase().trim();
        coformatted = (String) htCountry.get(country);

        if ((coformatted == null) || (coformatted.trim().equals(""))) {
            return country;
        }

        return coformatted;
    }

    public static void main(String[] args) {
        String test = "west-ger";
        String result = formatCountry(test);
        System.out.println("result ::" + result);

    }

}
