/*
 * Created on Aug 26, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package org.ei.common;

import java.util.Enumeration;
import java.util.Hashtable;

import org.apache.oro.text.perl.Perl5Util;

/**
 * @author Tsolovye
 *
 *         TODO To change the template for this generated type comment go to Window - Preferences - Java - Code Style - Code Templates
 */
public class CountryFormatter {
    private static Perl5Util perl = new Perl5Util();
    private static Hashtable<String, String> htCountry = new Hashtable<String, String>();
    static {
        htCountry.put("(india)", "india");
        htCountry.put("(sri lanka)", "sri lanka");
        htCountry.put("ar", "argentina");
        htCountry.put("ay", "antarctica");
        htCountry.put("af", "afghanistan");
        htCountry.put("afghan", "afghanistan");
        htCountry.put("afghanistan", "afghanistan");
        htCountry.put("alaska", "united states ");
        htCountry.put("albania", "albania");
        htCountry.put("albany", "united states");
        htCountry.put("alberta", "canada");
        htCountry.put("alger", "algeria");
        htCountry.put("algeria", "algeria");
        htCountry.put("algeria", "algeria");
        htCountry.put("algerie", "algeria");
        htCountry.put("amernia", "armenia");
        htCountry.put("andorra", "andorra");
        htCountry.put("angola", "angola");
        htCountry.put("antarct", "antarctica");
        htCountry.put("antarctica", "antarctica");
        htCountry.put("arg", "argentina");
        htCountry.put("argen", "argentina");
        htCountry.put("argent", "argentina");
        htCountry.put("argentina", "argentina");
        htCountry.put("armenia", "armenia");
        htCountry.put("athens", "greece");
        htCountry.put("au", "austria");
        htCountry.put("australia", "australia");
        htCountry.put("austria", "austria");
        htCountry.put("azerb", "azerbaijan");
        htCountry.put("azerbaidzhan", "azerbaijan");
        htCountry.put("azerbaijan", "azerbaijan");
        htCountry.put("azerbaijan republic", "azerbaijan");
        htCountry.put("azerbajdzhan", "azerbaijan");
        htCountry.put("belg", "belgium");
        htCountry.put("bras", "brazil");
        htCountry.put("braz", "brazil");
        htCountry.put("bssr", "belarus");
        htCountry.put("bahamas", "bahamas");
        htCountry.put("bahrain", "bahrain");
        htCountry.put("bahrein", "bahrain");
        htCountry.put("baku", "russia");
        htCountry.put("bangladesh", "bangladesh");
        htCountry.put("barbados", "barbados");
        htCountry.put("barcelona", "spain");
        htCountry.put("begium", "belgium");
        htCountry.put("beijing", "china");
        htCountry.put("bel", "belgium");
        htCountry.put("belarus", "belarus");
        htCountry.put("belarus'", "belarus");
        htCountry.put("belg", "belgium");
        htCountry.put("belgi", "belgium");
        htCountry.put("belgique", "belgium");
        htCountry.put("belgium", "belgium");
        htCountry.put("belize", "belize");
        htCountry.put("belorus", "belarus");
        htCountry.put("belorussia", "belarus");
        htCountry.put("benin", "china");
        htCountry.put("bermuda", "bermuda");
        htCountry.put("bhutan", "bhutan");
        htCountry.put("boliv", "bolivia");
        htCountry.put("bolivia", "bolivia");
        htCountry.put("bologna", "italy");
        htCountry.put("bombay", "india");
        htCountry.put("bosnia", "bosnia and herzegovina");
        htCountry.put("bosnia and herzegovina", "bosnia and herzegovina");
        htCountry.put("bosnia and herzegowina", "bosnia and herzegovina");
        htCountry.put("bosnia-herczegovina", "bosnia and herzegovina");
        htCountry.put("bosnia-herczegrovna", "bosnia and herzegovina");
        htCountry.put("bosnia-herz", "bosnia and herzegovina");
        htCountry.put("botswana", "botswana");
        htCountry.put("bra", "brazil");
        htCountry.put("bras", "brazil");
        htCountry.put("brasil", "brazil");
        htCountry.put("bratislava", " ");
        htCountry.put("braz", "brazil");
        htCountry.put("brazil", "brazil");
        htCountry.put("britain", "united kingdom");
        htCountry.put("british virgin islands", "british virgin islands");
        htCountry.put("british virgin isls", "british virgin islands");
        htCountry.put("brunei", "brunei");
        htCountry.put("brunei darussalam", "brunei");
        htCountry.put("brussels", "belgium");
        htCountry.put("bryansk", "russia");
        htCountry.put("bug", "bulgaria");
        htCountry.put("bul", "bulgaria");
        htCountry.put("bulg", "bulgaria");
        htCountry.put("bulgaria", "bulgaria");
        htCountry.put("bulgarien", "bulgaria");
        htCountry.put("burma", "burma");
        htCountry.put("burundi", "burundi");
        htCountry.put("byelorussia", "belarus");
        htCountry.put("ca", "canada");
        htCountry.put("can", "canada");
        htCountry.put("ch", "china");
        htCountry.put("china", "china");
        htCountry.put("co", "colombia");
        htCountry.put("cs", "costa rica");
        htCountry.put("czech repub", "czechoslovakia");
        htCountry.put("cairo", "egypt");
        htCountry.put("calabria", "italy");
        htCountry.put("cambodia", "cambodia");
        htCountry.put("cameron", "cameroon");
        htCountry.put("cameroon", "cameroon");
        htCountry.put("cameroun", "cameroon");
        htCountry.put("can", "canada");
        htCountry.put("cancan", "canada");
        htCountry.put("cana", "china");
        htCountry.put("canada", "canada");
        htCountry.put("cayman island", "cayman islands");
        htCountry.put("cayman islands", "cayman islands");
        htCountry.put("cent afr repub", "central african republic");
        htCountry.put("central african republic", "central african republic");
        htCountry.put("chad", "chad");
        htCountry.put("chiina", "china");
        htCountry.put("chile", "chile");
        htCountry.put("chin", "china");
        htCountry.put("china", "china");
        htCountry.put("china;china", "china");
        htCountry.put("china;china;china", "china");
        htCountry.put("chine", "china");
        htCountry.put("chinese", "china");
        htCountry.put("chna", "china");
        htCountry.put("cina", "china");
        htCountry.put("cleveland", "united states");
        htCountry.put("col", "colombia");
        htCountry.put("colo", "colombia");
        htCountry.put("colom", "colombia");
        htCountry.put("colomb", "colombia");
        htCountry.put("colombia", "colombia");
        htCountry.put("colorado", "united states");
        htCountry.put("columb", "colombia");
        htCountry.put("columbia", "colombia");
        htCountry.put("con", "congo");
        htCountry.put("congo", "congo");
        htCountry.put("costa rica", "costa rica");
        htCountry.put("crete", "greece");
        htCountry.put("croatia", "croatia");
        htCountry.put("cuba", "cuba");
        htCountry.put("cyprus", "cyprus");
        htCountry.put("czec", "czechoslovakia");
        htCountry.put("czech", "czechoslovakia");
        htCountry.put("czech repub", "czech republic");
        htCountry.put("czech republic", "czech republic");
        htCountry.put("czecho", "czechoslovakia");
        htCountry.put("czechos", "czechoslovakia");
        htCountry.put("czechosl", "czechoslovakia");
        htCountry.put("czechoslovakia", "czechoslovakia");
        htCountry.put("czeck", "czechoslovakia");
        htCountry.put("czesch", "czechoslovakia");
        htCountry.put("den", "denmark");
        htCountry.put("daenemark", "denmark");
        htCountry.put("den", "denmark");
        htCountry.put("denm", "denmark");
        htCountry.put("denmark", "denmark");
        htCountry.put("deutschland", "german democratic republic");
        htCountry.put("domin repub", "dominican republic");
        htCountry.put("dominica", "dominican republic");
        htCountry.put("dominican republic", "dominican republic");
        htCountry.put("donetsk", "russia");
        htCountry.put("eg", "egypt");
        htCountry.put("egypt", "egypt");
        htCountry.put("engl", "united kingdom");
        htCountry.put("england", "united kingdom");
        htCountry.put("engl", "united kingdom");
        htCountry.put("east ger", "german democratic republic");
        htCountry.put("east ger", "german democratic republic");
        htCountry.put("ecuador", "ecuador");
        htCountry.put("edinburgh", "united kingdom");
        htCountry.put("el salvador", "el salvador");
        htCountry.put("emgl", "united kingdom");
        htCountry.put("eng", "united kingdom");
        htCountry.put("engl", "united kingdom");
        htCountry.put("engl   ", "united kingdom");
        htCountry.put("engl.", "united kingdom");
        htCountry.put("england", "united kingdom");
        htCountry.put("engle", "united kingdom");
        htCountry.put("enlgh", "united kingdom");
        htCountry.put("equatorial guinea", "equatorial guinea");
        htCountry.put("eqypt", "egypt");
        htCountry.put("espagne", "spain");
        htCountry.put("espana", "spain");
        htCountry.put("estonia", "estonia");
        htCountry.put("ethiop", "ethiopia");
        htCountry.put("ethiopia", "ethiopia");
        htCountry.put("fin", "finland");
        htCountry.put("finl", "finland");
        htCountry.put("fl", "finland");
        htCountry.put("fr", "france");
        htCountry.put("frg", "france");
        htCountry.put("faroe islands", "faroe islands");
        htCountry.put("fed rep ger", "germany federal republic");
        htCountry.put("federal republic of ger", "germany federal republic");
        htCountry.put("federal republic of germany", "germany federal republic");
        htCountry.put("federated states of micronesia", " ");
        htCountry.put("fiji", "fiji");
        htCountry.put("fin", "finland");
        htCountry.put("findl", "finland");
        htCountry.put("finl", "finland");
        htCountry.put("finland", "finland");
        htCountry.put("finnl", "finland");
        htCountry.put("florida", "united states");
        htCountry.put("fr", "france");
        htCountry.put("fr ", "france");
        htCountry.put("fra", "france");
        htCountry.put("framce", "france");
        htCountry.put("france", "france");
        htCountry.put("fuji islands", "fiji");
        htCountry.put("ga", "gambia");
        htCountry.put("gb", "gabon");
        htCountry.put("greece", "greece");
        htCountry.put("gabon", "gabon");
        htCountry.put("gambia", "gambia");
        htCountry.put("georgia", "georgia");
        htCountry.put("ger", "germany");
        htCountry.put("germ", "germany");
        htCountry.put("german democratic republic", "german democratic republic");
        htCountry.put("germany", "germany");
        htCountry.put("germany, federal republic", "germany federal republic");
        htCountry.put("ghana", "ghana");
        htCountry.put("glasgow", "united kingdom");
        htCountry.put("goldsztejn, eduardo", " ");
        htCountry.put("grand duchy of luxembourg", "luxembourg");
        htCountry.put("gre", "greece");
        htCountry.put("greace", "greece");
        htCountry.put("great britain", "united kingdom");
        htCountry.put("grece", "greece");
        htCountry.put("greece", "greece");
        htCountry.put("greenland", "greenland");
        htCountry.put("grenada", "grenada");
        htCountry.put("guadeloupe", "guadeloupe");
        htCountry.put("guam", "guam");
        htCountry.put("guatem", "guatemala");
        htCountry.put("guatemala", "guatemala");
        htCountry.put("guinea", "guinea");
        htCountry.put("guinena", "guinea");
        htCountry.put("hamburg", "germany");
        htCountry.put("hawaii", "united states");
        htCountry.put("hol", "netherlands");
        htCountry.put("holland", "netherlands");
        htCountry.put("honduras", "honduras");
        htCountry.put("hong kong", "hong kong");
        htCountry.put("hun", "hungary");
        htCountry.put("hung", "hungary");
        htCountry.put("hungary", "hungary");
        htCountry.put("in", "india");
        htCountry.put("india", "india");
        htCountry.put("is", "israel");
        htCountry.put("isr", "israel");
        htCountry.put("italy", "italy");
        htCountry.put("ice", "iceland");
        htCountry.put("icel", "iceland");
        htCountry.put("iceland", "iceland");
        htCountry.put("in", "india");
        htCountry.put("ind", "india");
        htCountry.put("india", "india");
        htCountry.put("india.", "india");
        htCountry.put("indiana", "united states");
        htCountry.put("indone", "indonesia");
        htCountry.put("indones", "indonesia");
        htCountry.put("indonesia", "indonesia");
        htCountry.put("inida", "india");
        htCountry.put("iran", "iran");
        htCountry.put("iraq", "iraq");
        htCountry.put("ire", "ireland");
        htCountry.put("irel", "ireland");
        htCountry.put("ireland", "ireland");
        htCountry.put("irkutsk", "russia");
        htCountry.put("is", "isreal");
        htCountry.put("isr", "israel");
        htCountry.put("israel", "israel");
        htCountry.put("isrl", "israel");
        htCountry.put("istanbul, turk", "turkey");
        htCountry.put("ita", "italy");
        htCountry.put("italy", "italy");
        htCountry.put("ital", "italy");
        htCountry.put("italia", "italy");
        htCountry.put("italie", "italy");
        htCountry.put("italy", "italy");
        htCountry.put("ivory coast", "ivory coast");
        htCountry.put("japan", "japan");
        htCountry.put("jp", "japan");
        htCountry.put("jpn", "japan");
        htCountry.put("jam", "jamaica");
        htCountry.put("jamaica", "jamaica");
        htCountry.put("jap", "japan");
        htCountry.put("japan", "japan");
        htCountry.put("japn", "japan");
        htCountry.put("jerusalem", "israel");
        htCountry.put("jordan", "jordan");
        htCountry.put("jordon", "jordan");
        htCountry.put("jpan", "japan");
        htCountry.put("jpnjpn", "japan");
        htCountry.put("jugosl", "yugoslavia");
        htCountry.put("jugoslaviya", "yugoslavia");
        htCountry.put("jugoslawien", "yugoslavia");
        htCountry.put("kaz", "kazakhstan");
        htCountry.put("kazakh", "kazakhstan");
        htCountry.put("kazakhastan", "kazakhstan");
        htCountry.put("kazakhstan", "kazakhstan");
        htCountry.put("kazakstan", "kazakhstan");
        htCountry.put("kazan", "kazakhstan");
        htCountry.put("kenya", "kenya");
        htCountry.put("kiev", "ukraine");
        htCountry.put("kirg", "kyrgyzstan");
        htCountry.put("kirgizia", "kyrgyzstan");
        htCountry.put("korea", "korea, republic of");
        htCountry.put("korea (south)", "korea, republic of");
        htCountry.put("kuwait", "kuwait");
        htCountry.put("kyrgyzstan", "kyrgyzstan");
        htCountry.put("laos", "cambodia");
        htCountry.put("lat", "latvia");
        htCountry.put("latvia", "latvia");
        htCountry.put("leban", "lebanon");
        htCountry.put("lebanan", "lebanon");
        htCountry.put("lebanon", "lebanon");
        htCountry.put("leningrad", "russia");
        htCountry.put("lesotho", "lesotho");
        htCountry.put("liberia", "liberia");
        htCountry.put("libya", "libya");
        htCountry.put("libyan arab jamahiriya", "libya");
        htCountry.put("liechstenstein", "liechtenstein");
        htCountry.put("liechtenstein", "liechtenstein");
        htCountry.put("lit", "lithuania");
        htCountry.put("lith", "lithuania");
        htCountry.put("lithuania", "lithuania");
        htCountry.put("lithuanian ssr", "lithuania");
        htCountry.put("litovskaya respublica", "lithuania");
        htCountry.put("lituania", "lithuania");
        htCountry.put("london", "united kingdom");
        htCountry.put("luxemb", "luxembourg");
        htCountry.put("luxembourg", "luxembourg");
        htCountry.put("luxemburg", "luxembourg");
        htCountry.put("macao", "china");
        htCountry.put("macau", "china");
        htCountry.put("maced", "macedonia");
        htCountry.put("macedonia", "macedonia");
        htCountry.put("madagascar", "madagascar");
        htCountry.put("malawi", "malawi");
        htCountry.put("malay", "malaysia");
        htCountry.put("malaya", "malaysia");
        htCountry.put("malays", "malaysia");
        htCountry.put("malaysi", "malaysia");
        htCountry.put("malaysia", "malaysia");
        htCountry.put("mali", "mali");
        htCountry.put("malta", "malta");
        htCountry.put("manitoba", "canada");
        htCountry.put("maroc", "morocco");
        htCountry.put("marocco", "morocco");
        htCountry.put("martinez, nelson", " ");
        htCountry.put("mauritania", "mauritania");
        htCountry.put("mauritius", "mauritius");
        htCountry.put("mex", "mexico");
        htCountry.put("mexi", "mexico");
        htCountry.put("mexico", "mexico");
        htCountry.put("minnesota", "united states");
        htCountry.put("missouri", "united states");
        htCountry.put("mold", "moldova");
        htCountry.put("moldavia", "moldova");
        htCountry.put("moldova", "moldova");
        htCountry.put("monaco", "monaco");
        htCountry.put("mongolia", "china");
        htCountry.put("moroc", "morocco");
        htCountry.put("morocco", "morocco");
        htCountry.put("morrocco", "morocco");
        htCountry.put("moscow", "russia");
        htCountry.put("moscow region", "russia");
        htCountry.put("mozambique", "mozambique");
        htCountry.put("munich", "germany");
        htCountry.put("n korea", "Korea, People's Democratic Rep");
        htCountry.put("n z", "new zealand");
        htCountry.put("n zea", "new zealand");
        htCountry.put("n zeal", "new zealand");
        htCountry.put("n.e. china", "china");
        htCountry.put("nc", "new caledonia");
        htCountry.put("nj", "united states");
        htCountry.put("nl", "netherlands");
        htCountry.put("norw", "norway");
        htCountry.put("norway", "norway");
        htCountry.put("norway", "norway");
        htCountry.put("ny", "united states");
        htCountry.put("nz", "new zealand");
        htCountry.put("namibia", "namibia");
        htCountry.put("nepal", "nepal");
        htCountry.put("neth", "netherlands");
        htCountry.put("neth ", "netherlands");
        htCountry.put("nether", "netherlands");
        htCountry.put("netherl", "netherlands");
        htCountry.put("netherlands", "netherlands");
        htCountry.put("nethl", "netherlands");
        htCountry.put("neths", "netherlands");
        htCountry.put("new caledonia", "new caledonia");
        htCountry.put("new guinea", "Papua New Guinea");
        htCountry.put("new jersey", "united states");
        htCountry.put("new mex", "united states");
        htCountry.put("new mexico", "united states");
        htCountry.put("new york", "united states");
        htCountry.put("new zeal", "new zealand");
        htCountry.put("new zealand", "new zealand");
        htCountry.put("nicar", "nicaragua");
        htCountry.put("nicaragua", "nicaragua");
        htCountry.put("niger", "nigeria");
        htCountry.put("nigeria", "nigeria");
        htCountry.put("north korea", "Korea, People's Democratic Rep");
        htCountry.put("norw", "norway");
        htCountry.put("norway", "norway");
        htCountry.put("norway", "norway");
        htCountry.put("nz", "new zealand");
        htCountry.put("odessa", "ukraine");
        htCountry.put("ohio", "united states");
        htCountry.put("okinawa", "japan");
        htCountry.put("oman", "oman");
        htCountry.put("oregon", "united states");
        htCountry.put("orlanda", "united states");
        htCountry.put("osaka", "japan");
        htCountry.put("p. r. china", "china");
        htCountry.put("p.r. china", "china");
        htCountry.put("p.r.c.", "china");
        htCountry.put("pol", "poland");
        htCountry.put("pr china", "china");
        htCountry.put("pak", "pakistan");
        htCountry.put("pakistan", "pakistan");
        htCountry.put("palestine", "palestine");
        htCountry.put("panama", "panama");
        htCountry.put("papau new guinea", "papua new guinea");
        htCountry.put("papua new guinea", "papua new guinea");
        htCountry.put("parag", "paraguay");
        htCountry.put("paraguay", "paraguay");
        htCountry.put("peking", "china");
        htCountry.put("people's democr repub of yemen", "yemen");
        htCountry.put("people's republic of china", "china");
        htCountry.put("peoples republic of china", "china");
        htCountry.put("peoples republic of china", "china");
        htCountry.put("peru", "peru");
        htCountry.put("phil", "philippines");
        htCountry.put("philip", "philippines");
        htCountry.put("philipp", "philippines");
        htCountry.put("philippines", "philippines");
        htCountry.put("phillipp", "philippines");
        htCountry.put("pol", "poland");
        htCountry.put("poland", "poland");
        htCountry.put("porsgrunn norway", "norway");
        htCountry.put("port", "portugal");
        htCountry.put("portl", "portugal");
        htCountry.put("portugal", "portugal");
        htCountry.put("puerto rico", "puerto rico");
        htCountry.put("qatar", "qatar");
        htCountry.put("ro", "romania");
        htCountry.put("russia", "russia");
        htCountry.put("rep. germany", "germany");
        htCountry.put("republic of china", "china");
        htCountry.put("republic of ger", "germany");
        htCountry.put("republic of germany", "germany");
        htCountry.put("republic of korea", "Korea, Republic of");
        htCountry.put("republic of s afr", "south africa");
        htCountry.put("republic of south afr", "south africa");
        htCountry.put("republic of south africa", "south africa");
        htCountry.put("rissia", "russia");
        htCountry.put("rom", "romania");
        htCountry.put("roma", "romania");
        htCountry.put("romania", "romania");
        htCountry.put("rome", "romania");
        htCountry.put("rumania", "romania");
        htCountry.put("rumanien", "romania");
        htCountry.put("rus", "russia");
        htCountry.put("rusia", "russia");
        htCountry.put("russ", "russia");
        htCountry.put("russia", "russia");
        htCountry.put("russia", "russia");
        htCountry.put("russian", "russia");
        htCountry.put("russian federation", "russia");
        htCountry.put("rwanda", "rwanda");
        htCountry.put("s a", "south africa");
        htCountry.put("s af", "south africa");
        htCountry.put("s afr", "south africa");
        htCountry.put("s afri", "south africa");
        htCountry.put("s africa", "south africa");
        htCountry.put("s arabia", "saudi arabia");
        htCountry.put("s korea", "Korea, Republic of");
        htCountry.put("s. afr", "south africa");
        htCountry.put("s. africa", "south africa");
        htCountry.put("s. korea", "Korea, Republic of");
        htCountry.put("s.afr", "south africa");
        htCountry.put("sa", "saudi arabia");
        htCountry.put("se", "seychelles");
        htCountry.put("sf", "south africa");
        htCountry.put("south korea", "Korea, Republic of");
        htCountry.put("spain", "spain");
        htCountry.put("ssr", "ussr");
        htCountry.put("swed", "sweden");
        htCountry.put("switz", "switzerland");
        htCountry.put("sweden", "sweden");
        htCountry.put("samoa", "samoa");
        htCountry.put("san marino", "san marino");
        htCountry.put("saskatchewan", " ");
        htCountry.put("saudi", "saudi arabia");
        htCountry.put("saudi arabi", "saudi arabia");
        htCountry.put("saudi arabia", "saudi arabia");
        htCountry.put("saudi arbia", "saudi arabia");
        htCountry.put("saudi arubia", "saudi arabia");
        htCountry.put("saudi-arabia", "saudi arabia");
        htCountry.put("saudia arabia", "saudi arabia");
        htCountry.put("sauid arabia", "saudi arabia");
        htCountry.put("sauidi arabia", "saudi arabia");
        htCountry.put("scolt", "united kingdom");
        htCountry.put("scot", "united kingdom");
        htCountry.put("scotl", "united kingdom");
        htCountry.put("scotl  ", "united kingdom");
        htCountry.put("scotlusa", "united kingdom");
        htCountry.put("scotland", "united kingdom");
        htCountry.put("scott", "united kingdom");
        htCountry.put("sctl", "united kingdom");
        htCountry.put("senegal", "senegal");
        htCountry.put("seoul", "Korea, Republic of");
        htCountry.put("serbia", "serbia");
        htCountry.put("serbia and montenegro", "serbia");
        htCountry.put("seychelles", "seychelles");
        htCountry.put("sf", "south africa");
        htCountry.put("siberia", "russia");
        htCountry.put("sierra leone", "sierra leone");
        htCountry.put("sing", "singapore");
        htCountry.put("singaphore", "singapore");
        htCountry.put("singapore", "singapore");
        htCountry.put("singapore 0511", "singapore");
        htCountry.put("singpore", "singapore");
        htCountry.put("sir lanka", "sri lanka");
        htCountry.put("slovak", "slovakia");
        htCountry.put("slovak republic", "slovakia");
        htCountry.put("slovakia", "slovakia");
        htCountry.put("slovakiya", "slovakia");
        htCountry.put("slovenia", "slovenia");
        htCountry.put("slovenija", "slovenia");
        htCountry.put("somalia", "somalia");
        htCountry.put("south af", "south africa");
        htCountry.put("south afr", "south africa");
        htCountry.put("south afri", "south africa");
        htCountry.put("south africa", "south africa");
        htCountry.put("sp", "spain");
        htCountry.put("spain", "spain");
        htCountry.put("spn", "spain");
        htCountry.put("sri lanka", "sri lanka");
        htCountry.put("state of bahrain", "bahrain");
        htCountry.put("state of qatar", "qatar");
        htCountry.put("sudan", "sudan");
        htCountry.put("sultanate of oman", "oman");
        htCountry.put("suriname", "suriname");
        htCountry.put("swazil", "swaziland");
        htCountry.put("swaziland", "swaziland");
        htCountry.put("swe", "sweden");
        htCountry.put("swed", "sweden");
        htCountry.put("swedswed", "sweden");
        htCountry.put("sweden", "sweden");
        htCountry.put("swedish", "sweden");
        htCountry.put("swez", "switzerland");
        htCountry.put("swit", "switzerland");
        htCountry.put("switz", "switzerland");
        htCountry.put("switzer", "switzerland");
        htCountry.put("switzerl", "switzerland");
        htCountry.put("switzerland", "switzerland");
        htCountry.put("switzl", "switzerland");
        htCountry.put("sydney", "australia");
        htCountry.put("syria", "syria");
        htCountry.put("syrian arab republic", "syria");
        htCountry.put("turk", "turkey");
        htCountry.put("tx", "Turkmenistan");
        htCountry.put("taiw", "taiwan");
        htCountry.put("taiwain", "taiwan");
        htCountry.put("taiwan", "taiwan");
        htCountry.put("tajikistan", "tajikistan");
        htCountry.put("tanzan", "tanzania, united republic of");
        htCountry.put("tanzania", "tanzania, united republic of");
        htCountry.put("tawain", "taiwan");
        htCountry.put("th", "thailand");
        htCountry.put("thail", "thailand");
        htCountry.put("thailand", "thailand");
        htCountry.put("the neth", "netherlands");
        htCountry.put("the netherlands", "netherlands");
        htCountry.put("thial", "thailand");
        htCountry.put("tiawan", "taiwan");
        htCountry.put("tokyo", "japan");
        htCountry.put("trinidad", "trinidad and tobago");
        htCountry.put("trinidad & tobago", "trinidad and tobago");
        htCountry.put("trinidad &amp; tobago", "trinidad and tobago");
        htCountry.put("trinidad (w.i.)", "trinidad and tobago");
        htCountry.put("trinidad and tobago", "trinidad and tobago");
        htCountry.put("tunis", "tunisia");
        htCountry.put("tunisia", "tunisia");
        htCountry.put("tunisie", "tunisia");
        htCountry.put("turk", "turkey");
        htCountry.put("turkey", "turkey");
        htCountry.put("u.k.", "united kingdom");
        htCountry.put("u.s.a.", "united states");
        htCountry.put("u.s.s.r.", "ussr");
        htCountry.put("uk", "united kingdom");
        htCountry.put("ukr ssr", "ukraine");
        htCountry.put("urss", "ussr");
        htCountry.put("usa", "united states");
        htCountry.put("usa0704", "united states");
        htCountry.put("usausa", "united states");
        htCountry.put("ussr", "ussr");
        htCountry.put("ussr acad of sciences", "ussr");
        htCountry.put("usa", "united states");
        htCountry.put("uganda", "uganda");
        htCountry.put("uk", "united kingdom");
        htCountry.put("ukaine", "ukraine");
        htCountry.put("ukr", "ukraine");
        htCountry.put("ukrssr", "ukraine");
        htCountry.put("ukraine", "ukraine");
        htCountry.put("ukrainian ssr", "ukraine");
        htCountry.put("unite arab emirates", "united arab emirates");
        htCountry.put("united arab emirate", "united arab emirates");
        htCountry.put("united arab emirates", "united arab emirates");
        htCountry.put("united arabs emirates", "united arab emirates");
        htCountry.put("united kingdom", "united kingdom");
        htCountry.put("united states", "united states");
        htCountry.put("united states minor outlying islands", "united states");
        htCountry.put("urug", "uruguay");
        htCountry.put("uruguay", "uruguay");
        htCountry.put("uzb", "uzbekistan");
        htCountry.put("uzbekhistan", "uzbekistan");
        htCountry.put("uzbekistan", "uzbekistan");
        htCountry.put("ven", "venezuela");
        htCountry.put("vene'z", "venezuela");
        htCountry.put("venez", "venezuela");
        htCountry.put("venezuela", "venezuela");
        htCountry.put("venz", "venezuela");
        htCountry.put("vienna", "austria");
        htCountry.put("viet", "viet nam");
        htCountry.put("viet nam", "viet nam");
        htCountry.put("vietnam", "viet nam");
        htCountry.put("virginia", "united states");
        htCountry.put("vitnam", "viet nam");
        htCountry.put("w ger", "germany");
        htCountry.put("w-ger", "germany");
        htCountry.put("w. aust", "germany");
        htCountry.put("w. ger", "germany");
        htCountry.put("w. germany", "germany");
        htCountry.put("wales", "united kingdom");
        htCountry.put("wales", "united kingdom");
        htCountry.put("wast ger", "germany");
        htCountry.put("west australia", "australia");
        htCountry.put("west ger", "germany");
        htCountry.put("west ger.", "germany");
        htCountry.put("west gerwest ger", "germany");
        htCountry.put("west germ", "germany");
        htCountry.put("west germany", "germany");
        htCountry.put("west-ger", "germany");
        htCountry.put("western aust", "australia");
        htCountry.put("western australia", "australia");
        htCountry.put("wet ger", "germany");
        htCountry.put("yemen", "yemen");
        htCountry.put("yemen arab repub", "yemen");
        htCountry.put("yemen arab republic", "yemen");
        htCountry.put("ygosl", "yugoslavia");
        htCountry.put("yogosl", "yugoslavia");
        htCountry.put("yogusl", "yugoslavia");
        htCountry.put("yug", "yugoslavia");
        htCountry.put("yugasl", "yugoslavia");
        htCountry.put("yugo", "yugoslavia");
        htCountry.put("yugol", "yugoslavia");
        htCountry.put("yugos", "yugoslavia");
        htCountry.put("yugosl", "yugoslavia");
        htCountry.put("yugoslyugosl", "yugoslavia");
        htCountry.put("yugoslavia", "yugoslavia");
        htCountry.put("yugsl", "yugoslavia");
        htCountry.put("yugsol", "yugoslavia");
        htCountry.put("yukon", "united states");
        htCountry.put("yvgosl", "yugoslavia");
        htCountry.put("zaire", "zaire");
        htCountry.put("zambia", "zambia");
        htCountry.put("zimbabwe", "zimbabwe");
        htCountry.put("zimbabwee", "zimbabwe");
        htCountry.put("zuerich", "switzerland");
        htCountry.put("zurich", "switzerland");
        htCountry.put("audi arabia", "saudi arabia");
        htCountry.put("can", "canada");
        htCountry.put("china", "china");
        htCountry.put("fr", "france");
        htCountry.put("west ger", "germany");

        htCountry.put("ad", "andorra");
        htCountry.put("ae", "united arab emirates");
        htCountry.put("af", "afghanistan");
        htCountry.put("ag", "antigua");
        htCountry.put("ai", "anguilla");
        htCountry.put("al", "albania");
        htCountry.put("am", "armenia");
        htCountry.put("an", "netherlands");
        htCountry.put("ao", "angola");
        htCountry.put("ap", "aripo");
        htCountry.put("aq", "antarctica");
        htCountry.put("ar", "argentina");
        htCountry.put("as", "american samoa");
        htCountry.put("at", "austria");
        htCountry.put("au", "australia");
        htCountry.put("aw", "aruba");
        htCountry.put("az", "azerbaijan");
        htCountry.put("ba", "bosnia and herzegovina");
        htCountry.put("bb", "barbados");
        htCountry.put("bd", "bangladesh");
        htCountry.put("be", "belgium");
        htCountry.put("bf", "burkina faso");
        htCountry.put("bg", "bulgaria");
        htCountry.put("bh", "bahrain");
        htCountry.put("bi", "burundi");
        htCountry.put("bj", "benin");
        htCountry.put("bm", "bermuda");
        htCountry.put("bn", "brunie");
        htCountry.put("bo", "bolivia");
        htCountry.put("br", "brazil");
        htCountry.put("bs", "bahamas");
        htCountry.put("bt", "bhutan");
        htCountry.put("bu", "burma");
        htCountry.put("bv", "bouvet island");
        htCountry.put("bw", "botswana");
        htCountry.put("by", "belarus");
        htCountry.put("bz", "belize");
        htCountry.put("ca", "canada");
        htCountry.put("cc", "cocos (keeling) islands");
        htCountry.put("cf", "central african republic");
        htCountry.put("cg", "congo");
        htCountry.put("ch", "switzerland");
        htCountry.put("ci", "ivory coast");
        htCountry.put("ck", "cook islands");
        htCountry.put("cl", "chile");
        htCountry.put("cm", "cameroon");
        htCountry.put("cn", "china");
        htCountry.put("co", "colombia");
        htCountry.put("cr", "costa rica");
        htCountry.put("cs", "czechoslovakia");
        htCountry.put("cu", "cuba");
        htCountry.put("cv", "cape verde");
        htCountry.put("cx", "christmas island");
        htCountry.put("cy", "cyprus");
        htCountry.put("cz", "czech republic");
        htCountry.put("dd", "german democratic republic");
        htCountry.put("de", "germany");
        htCountry.put("dj", "djibouti");
        htCountry.put("dk", "denmark");
        htCountry.put("dm", "dominica");
        htCountry.put("do", "dominican republic");
        htCountry.put("dz", "algeria");
        htCountry.put("ea", "eurasian patent office");
        htCountry.put("ec", "ecuador");
        htCountry.put("ee", "estonia");
        htCountry.put("eg", "egypt");
        htCountry.put("eh", "western sahara");
        htCountry.put("ep", "european patent office");
        htCountry.put("er", "eritrea");
        htCountry.put("es", "spain");
        htCountry.put("et", "ethiopia");
        htCountry.put("fi", "finland");
        htCountry.put("fj", "fiji");
        htCountry.put("fk", "falkland islands");
        htCountry.put("fm", "micronesia");
        htCountry.put("fo", "faroe islands");
        htCountry.put("fr", "france");
        htCountry.put("fx", "france, metropolitan");
        htCountry.put("ga", "gabon");
        htCountry.put("gb", "united kingdom");
        htCountry.put("gc", "gulf cooperation council");
        htCountry.put("gd", "grenada");
        htCountry.put("ge", "georgia");
        htCountry.put("gf", "french guiana");
        htCountry.put("gh", "ghana");
        htCountry.put("gi", "gibraltar");
        htCountry.put("gl", "greenland");
        htCountry.put("gm", "gambia");
        htCountry.put("gn", "guinea");
        htCountry.put("gp", "guadaloupe");
        htCountry.put("gq", "equatorial guinea");
        htCountry.put("gr", "greece");
        htCountry.put("gs", "south georgia and the south sandwich islands");
        htCountry.put("gt", "guatemala");
        htCountry.put("gu", "guam");
        htCountry.put("gw", "guinea-bissau");
        htCountry.put("gy", "guyana");
        htCountry.put("hk", "hong kong");
        htCountry.put("hm", "heard & mcDonald islands");
        htCountry.put("hn", "honduras");
        htCountry.put("hr", "croatia");
        htCountry.put("ht", "haiti");
        htCountry.put("hu", "hungary");
        htCountry.put("id", "indonesia");
        htCountry.put("ie", "ireland");
        htCountry.put("il", "israel");
        htCountry.put("in", "india");
        htCountry.put("io", "british indian ocean territory");
        htCountry.put("iq", "iraq");
        htCountry.put("ir", "iran");
        htCountry.put("is", "iceland");
        htCountry.put("it", "italy");
        htCountry.put("jm", "jamaica");
        htCountry.put("ja", "jamaica");
        htCountry.put("jo", "jordan");
        htCountry.put("jp", "japan");
        htCountry.put("ke", "kenya");
        htCountry.put("kg", "kyrgyzstan");
        htCountry.put("kh", "cambodia");
        htCountry.put("ki", "kiribati");
        htCountry.put("km", "comoros");
        htCountry.put("kn", "st. kitts and nevis");
        htCountry.put("kp", "korea, republic of");
        htCountry.put("kr", "korea, republic of");
        htCountry.put("kw", "kuwait");
        htCountry.put("ky", "cayman islands");
        htCountry.put("kz", "kazakhstan");
        htCountry.put("la", "laos");
        htCountry.put("lb", "lebanon");
        htCountry.put("lc", "saint lucia");
        htCountry.put("li", "liechtenstein");
        htCountry.put("lk", "sri lanka");
        htCountry.put("lr", "liberia");
        htCountry.put("ls", "lesotho");
        htCountry.put("lt", "lithuania");
        htCountry.put("lu", "luxembourg");
        htCountry.put("lv", "latvia");
        htCountry.put("ly", "libya");
        htCountry.put("ma", "morocco");
        htCountry.put("mc", "monaco");
        htCountry.put("md", "moldova");
        htCountry.put("mg", "madagascar");
        htCountry.put("mh", "marshall islands");
        htCountry.put("ml", "mali");
        htCountry.put("mm", "myanmar");
        htCountry.put("mn", "mogolia");
        htCountry.put("mo", "china");
        htCountry.put("mp", "northern mariana islands");
        htCountry.put("mq", "martinique");
        htCountry.put("mr", "mauritania");
        htCountry.put("ms", "monserrat");
        htCountry.put("mt", "malta");
        htCountry.put("mu", "mauritius");
        htCountry.put("mv", "maldives");
        htCountry.put("mw", "malawi");
        htCountry.put("mx", "mexico");
        htCountry.put("my", "malaysia");
        htCountry.put("mz", "mozambique");
        htCountry.put("na", "namibia");
        htCountry.put("nc", "new caledonia");
        htCountry.put("ne", "nigeria");
        htCountry.put("nf", "norfolk island");
        htCountry.put("ng", "nigeria");
        htCountry.put("ni", "nicaragua");
        htCountry.put("nl", "netherlands");
        htCountry.put("no", "norway");
        htCountry.put("np", "nepal");
        htCountry.put("nr", "nauru");
        htCountry.put("nt", "neutral zone");
        htCountry.put("nu", "niue");
        htCountry.put("nz", "new zealand");
        htCountry.put("oa", "oapi");
        htCountry.put("om", "oman");
        htCountry.put("pa", "panama");
        htCountry.put("pe", "peru");
        htCountry.put("pf", "french polynesia");
        htCountry.put("pg", "papua new guinea");
        htCountry.put("ph", "philippines");
        htCountry.put("pk", "pakistan");
        htCountry.put("pl", "poland");
        htCountry.put("pm", "st. pierre & miquelon");
        htCountry.put("pn", "pitcairn");
        htCountry.put("pr", "puerto rico");
        htCountry.put("pt", "portugal");
        htCountry.put("pw", "Palau");
        htCountry.put("py", "paraguay");
        htCountry.put("qa", "qatar");
        htCountry.put("re", "reunion");
        htCountry.put("ro", "romania");
        htCountry.put("ru", "russia");
        htCountry.put("rw", "rwanda");
        htCountry.put("sa", "saudi arabia");
        htCountry.put("sb", "solomon islands");
        htCountry.put("sc", "seychelles");
        htCountry.put("sd", "sudan");
        htCountry.put("se", "sweden");
        htCountry.put("sg", "singapore");
        htCountry.put("sh", "st. helena");
        htCountry.put("si", "slovenia");
        htCountry.put("sj", "svalbard and jan mayen islands");
        htCountry.put("sk", "slovakia");
        htCountry.put("sl", "sierra leone");
        htCountry.put("sm", "san marino");
        htCountry.put("sn", "senegal");
        htCountry.put("so", "somalia");
        htCountry.put("sr", "suriname");
        htCountry.put("st", "sao tome and principe");
        htCountry.put("su", "russia");
        htCountry.put("sv", "el salvador");
        htCountry.put("sy", "syria");
        htCountry.put("sz", "swaziland");
        htCountry.put("tc", "turks and caicos islands");
        htCountry.put("td", "chad");
        htCountry.put("tf", "french southern territories");
        htCountry.put("tg", "togo");
        htCountry.put("th", "thailand");
        htCountry.put("tj", "tajikistan");
        htCountry.put("tk", "tokelau");
        htCountry.put("tm", "turkmenistan");
        htCountry.put("tn", "tunisia");
        htCountry.put("to", "tonga");
        htCountry.put("tp", "east timor");
        htCountry.put("tr", "turkey");
        htCountry.put("tt", "trinidad and tobago");
        htCountry.put("tv", "tuvalu");
        htCountry.put("tw", "taiwan");
        htCountry.put("tz", "tanzania, united republic of");
        htCountry.put("ua", "ukraine");
        htCountry.put("ug", "uganda");
        htCountry.put("um", "united states");
        htCountry.put("us", "united states");
        htCountry.put("uy", "uruguay");
        htCountry.put("uz", "uzbekistan");
        htCountry.put("va", "vatican city");
        htCountry.put("vc", "saint vicent & the grenadines");
        htCountry.put("ve", "venezuela");
        htCountry.put("vg", "british virgin islands");
        htCountry.put("vi", "united states virgin islands");
        htCountry.put("vn", "viet nam");
        htCountry.put("vu", "vanuatu");
        htCountry.put("wf", "wallis and futuna islands");
        htCountry.put("wo", "wipo");
        htCountry.put("ws", "samoa");
        htCountry.put("yd", "yemen");
        htCountry.put("ye", "yemen");
        htCountry.put("yt", "mayotte");
        htCountry.put("yu", "yugoslavia");
        htCountry.put("za", "south africa");
        htCountry.put("zm", "zambia");
        htCountry.put("zr", "zaire");
        htCountry.put("zw", "zimbabwe");

        // three letters country code from new ani512.dtd

        htCountry.put("afg", "afghanistan");
        htCountry.put("alb", "albania");
        htCountry.put("dza", "algeria");
        htCountry.put("asm", "american samoa");
        htCountry.put("and", "andorra");
        htCountry.put("ago", "angola");
        htCountry.put("aia", "anguilla");
        htCountry.put("ata", "antarctica");
        htCountry.put("atg", "antigua");
        htCountry.put("arg", "argentina");
        htCountry.put("arm", "armenia");
        htCountry.put("abw", "aruba");
        htCountry.put("aus", "australia");
        htCountry.put("aut", "austria");
        htCountry.put("aze", "azerbaijan");
        htCountry.put("bhs", "bahamas");
        htCountry.put("bhr", "bahrain");
        htCountry.put("bgd", "bangladesh");
        htCountry.put("brb", "barbados");
        htCountry.put("blr", "belarus");
        htCountry.put("bel", "belgium");
        htCountry.put("blz", "belize");
        htCountry.put("ben", "benin");
        htCountry.put("bmu", "bermuda");
        htCountry.put("btn", "bhutan");
        htCountry.put("bol", "bolivia");
        htCountry.put("bih", "bosnia and herzegovina");
        htCountry.put("bwa", "botswana");
        htCountry.put("bvt", "bouvet island");
        htCountry.put("bra", "brazil");
        htCountry.put("iot", "british indian ocean territory");
        htCountry.put("brn", "brunei");
        htCountry.put("bgr", "bulgaria");
        htCountry.put("bfa", "burkina faso");
        htCountry.put("bdi", "burundi");
        htCountry.put("khm", "cambodia");
        htCountry.put("cmr", "cameroon");
        htCountry.put("can", "canada");
        htCountry.put("cpv", "cape verde");
        htCountry.put("cym", "cayman islands");
        htCountry.put("caf", "central african republic");
        htCountry.put("tcd", "chad");
        htCountry.put("chl", "chile");
        htCountry.put("chn", "china");
        htCountry.put("cxr", "christmas island");
        htCountry.put("cck", "cocos (keeling) islands");
        htCountry.put("col", "colombia");
        htCountry.put("com", "comoros");
        htCountry.put("cog", "congo");
        htCountry.put("cok", "cook islands");
        htCountry.put("cri", "costa rica");
        htCountry.put("civ", "ivory coast");
        htCountry.put("hrv", "croatia");
        htCountry.put("cub", "cuba");
        htCountry.put("cyp", "cyprus");
        htCountry.put("cze", "czech republic");
        htCountry.put("cod", "democratic republic congo");
        htCountry.put("dnk", "denmark");
        htCountry.put("dji", "djibouti");
        htCountry.put("dma", "dominica");
        htCountry.put("dom", "dominican republic");
        htCountry.put("ecu", "ecuador");
        htCountry.put("egy", "egypt");
        htCountry.put("slv", "el salvador");
        htCountry.put("gnq", "equatorial guinea");
        htCountry.put("eri", "eritrea");
        htCountry.put("est", "estonia");
        htCountry.put("eth", "ethiopia");
        htCountry.put("flk", "falkland islands");
        htCountry.put("fro", "faroe islands");
        htCountry.put("fsm", "micronesia");
        htCountry.put("fji", "fiji");
        htCountry.put("fin", "finland");
        htCountry.put("fra", "france");
        htCountry.put("guf", "french guiana");
        htCountry.put("pyf", "french polynesia");
        htCountry.put("atf", "french southern territories");
        htCountry.put("gab", "gabon");
        htCountry.put("gmb", "gambia");
        htCountry.put("geo", "georgia");
        htCountry.put("deu", "germany");
        htCountry.put("gha", "ghana");
        htCountry.put("gib", "gibraltar");
        htCountry.put("grc", "greece");
        htCountry.put("grl", "greenland");
        htCountry.put("grd", "grenada");
        htCountry.put("glp", "guadeloupe");
        htCountry.put("gum", "guam");
        htCountry.put("gtm", "guatemala");
        htCountry.put("gin", "guinea");
        htCountry.put("gnb", "guinea-bissau");
        htCountry.put("guy", "guyana");
        htCountry.put("hti", "haiti");
        htCountry.put("hmd", "heard & mcDonald islands");
        htCountry.put("hnd", "honduras");
        htCountry.put("hkg", "hong kong");
        htCountry.put("hun", "hungary");
        htCountry.put("isl", "iceland");
        htCountry.put("ind", "india");
        htCountry.put("idn", "indonesia");
        htCountry.put("irn", "iran");
        htCountry.put("irq", "iraq");
        htCountry.put("irl", "ireland");
        htCountry.put("isr", "israel");
        htCountry.put("ita", "italy");
        htCountry.put("jam", "jamaica");
        htCountry.put("jpn", "japan");
        htCountry.put("jor", "jordan");
        htCountry.put("kaz", "kazakhstan");
        htCountry.put("ken", "kenya");
        htCountry.put("kir", "kiribati");
        htCountry.put("kwt", "kuwait");
        htCountry.put("kgz", "kyrgyzstan");
        htCountry.put("lao", "laos");
        htCountry.put("lva", "latvia");
        htCountry.put("lbn", "lebanon");
        htCountry.put("lso", "lesotho");
        htCountry.put("lbr", "liberia");
        htCountry.put("lby", "libya");
        htCountry.put("lie", "liechtenstein");
        htCountry.put("ltu", "lithuania");
        htCountry.put("lux", "luxembourg");
        htCountry.put("mac", "china");
        htCountry.put("mkd", "macedonia");
        htCountry.put("mdg", "madagascar");
        htCountry.put("mwi", "malawi");
        htCountry.put("mys", "malaysia");
        htCountry.put("mdv", "maldives");
        htCountry.put("mli", "mali");
        htCountry.put("mlt", "malta");
        htCountry.put("mhl", "marshall islands");
        htCountry.put("mtq", "martinique");
        htCountry.put("mrt", "mauritania");
        htCountry.put("mus", "mauritius");
        htCountry.put("myt", "mayotte");
        htCountry.put("mex", "mexico");
        htCountry.put("mda", "moldova");
        htCountry.put("mco", "monaco");
        htCountry.put("mng", "mongolia");
        htCountry.put("mne", "montenegro");
        htCountry.put("msr", "montserrat");
        htCountry.put("mar", "morocco");
        htCountry.put("moz", "mozambique");
        htCountry.put("mmr", "myanmar");
        htCountry.put("nam", "namibia");
        htCountry.put("nru", "nauru");
        htCountry.put("npl", "nepal");
        htCountry.put("nld", "netherlands");
        htCountry.put("ant", "netherlands");
        htCountry.put("ncl", "new caledonia");
        htCountry.put("nzl", "new zealand");
        htCountry.put("nic", "nicaragua");
        htCountry.put("ner", "niger");
        htCountry.put("nga", "nigeria");
        htCountry.put("niu", "niue");
        htCountry.put("nfk", "norfolk island");
        htCountry.put("prk", "Korea, People's Democratic Rep");
        htCountry.put("mnp", "northern mariana islands");
        htCountry.put("nor", "norway");
        htCountry.put("omn", "oman");
        htCountry.put("pak", "pakistan");
        htCountry.put("plw", "palau");
        htCountry.put("pse", "palestine");
        htCountry.put("pan", "panama");
        htCountry.put("png", "papua new guinea");
        htCountry.put("pry", "paraguay");
        htCountry.put("per", "peru");
        htCountry.put("phl", "philippines");
        htCountry.put("pcn", "pitcairn");
        htCountry.put("pol", "poland");
        htCountry.put("prt", "portugal");
        htCountry.put("pri", "puerto rico");
        htCountry.put("qat", "qatar");
        htCountry.put("reu", "reunion");
        htCountry.put("twn", "taiwan");
        htCountry.put("rou", "romania");
        htCountry.put("rus", "russia");
        htCountry.put("rwa", "rwanda");
        htCountry.put("shn", "st. helena");
        htCountry.put("kna", "st. kitts and nevis");
        htCountry.put("lca", "saint lucia");
        htCountry.put("spm", "st. pierre & miquelon");
        htCountry.put("vct", "saint vicent & the grenadines");
        htCountry.put("wsm", "samoa");
        htCountry.put("smr", "san marino");
        htCountry.put("stp", "sao tome and principe");
        htCountry.put("sau", "saudi arabia");
        htCountry.put("sen", "senegal");
        htCountry.put("srb", "serbia");
        htCountry.put("syc", "seychelles");
        htCountry.put("sle", "sierra leone");
        htCountry.put("sgp", "singapore");
        htCountry.put("svk", "slovakia");
        htCountry.put("svn", "slovenia");
        htCountry.put("slb", "solomon islands");
        htCountry.put("som", "somalia");
        htCountry.put("zaf", "south africa");
        htCountry.put("sgs", "south georgia and the south sandwich islands");
        htCountry.put("kor", "Korea, Republic of");
        htCountry.put("esp", "spain");
        htCountry.put("lka", "sri lanka");
        htCountry.put("sdn", "sudan");
        htCountry.put("sur", "suriname");
        htCountry.put("sjm", "svalbard and jan mayen islands");
        htCountry.put("swz", "swaziland");
        htCountry.put("swe", "sweden");
        htCountry.put("che", "switzerland");
        htCountry.put("syr", "syria");
        htCountry.put("twn", "taiwan");
        htCountry.put("tjk", "tajikistan");
        htCountry.put("tza", "tanzania, united republic of");
        htCountry.put("tha", "thailand");
        htCountry.put("tls", "timor-leste");
        htCountry.put("tgo", "togo");
        htCountry.put("tkl", "tokelau");
        htCountry.put("ton", "tonga");
        htCountry.put("tto", "trinidad and tobago");
        htCountry.put("tun", "tunisia");
        htCountry.put("tur", "turkey");
        htCountry.put("tkm", "turkmenistan");
        htCountry.put("tca", "turks and caicos islands");
        htCountry.put("tuv", "tuvalu");
        htCountry.put("uga", "uganda");
        htCountry.put("ukr", "ukraine");
        htCountry.put("are", "united arab emirates");
        htCountry.put("gbr", "united kingdom");
        htCountry.put("usa", "united states");
        htCountry.put("umi", "united states");
        htCountry.put("ury", "uruguay");
        htCountry.put("uzb", "uzbekistan");
        htCountry.put("vut", "vanuatu");
        htCountry.put("ven", "venezuela");
        htCountry.put("vnm", "viet nam");
        htCountry.put("vgb", "british virgin islands");
        htCountry.put("vir", "united states virgin islands");
        htCountry.put("wlf", "wallis and futuna islands");
        htCountry.put("esh", "western sahara");
        htCountry.put("yem", "yemen");
        htCountry.put("zmb", "zambia");
        htCountry.put("zwe", "zimbabwe");
    }

    public static String getCountry(String af) {
        Enumeration<String> en = htCountry.keys();
        while (en.hasMoreElements()) {
            String next = (String) en.nextElement();
            if (perl.match("/,\\s*" + next + "$/i", af.trim())) {
                String s = (String) htCountry.get(next);
                if (s.trim().length() > 0) {
                    return s;
                } else {
                    return null;
                }
            }
        }

        return null;
    }

    public static String formatCountry(String country) {
        if ((country == null) || (country.trim().equals(""))) {
            return null;
        }

        String coformatted = null;

        country = country.toLowerCase().trim();
        coformatted = (String) htCountry.get(country);

        if ((coformatted == null) || (coformatted.trim().equals(""))) {
            return country;
        }

        return coformatted;
    }

    public static String formatCase(String country) {
        if (country != null) {
            StringBuffer buf = new StringBuffer();
            String[] words = country.split(" ");

            for (int i = 0; i < words.length; i++) {
                String word = words[i];
                if (i > 0) {
                    buf.append(" ");
                }

                if (!word.equals("the") && !word.equals("and") && !word.equals("of")) {
                    String firstChar = word.substring(0, 1);
                    buf.append(firstChar.toUpperCase());
                    buf.append(word.substring(1));
                } else {
                    buf.append(word);
                }
            }

            return buf.toString();
        }

        return null;
    }

    public static void main(String[] args) {
        String test = "west-ger";
        String result = formatCountry(test);
        System.out.println("result ::" + result);

    }
}
