package org.ei.common;
import java.util.Hashtable;

public class Language
{
	public static Hashtable iso639_language = new Hashtable();

	static
	{
		iso639_language.put("AA","Afar");
		iso639_language.put("AB","Abkhazian");
		iso639_language.put("AF","Afrikaans");
		iso639_language.put("AM","Amharic");
		iso639_language.put("AR","Arabic");
		iso639_language.put("AS","Assamese");
		iso639_language.put("AY","Aymara");
		iso639_language.put("AZ","Azerbaijani");
		iso639_language.put("BA","Bashkir");
		iso639_language.put("BE","Byelorussian");
		iso639_language.put("BG","Bulgarian");
		iso639_language.put("BH","Bihari");
		iso639_language.put("BI","Bislama");
		iso639_language.put("BN","Bengali");
		iso639_language.put("BO","Tibetan");
		iso639_language.put("BR","Breton");
		iso639_language.put("CA","Catalan");
		iso639_language.put("CO","Corsican");
		iso639_language.put("CS","Czech");
		iso639_language.put("CY","Welsh");
		iso639_language.put("DA","Danish");
		iso639_language.put("DE","German");
		iso639_language.put("DZ","Bhutani");
		iso639_language.put("EL","Greek");
		iso639_language.put("EN","English");
		iso639_language.put("EO","Esperanto");
		iso639_language.put("ES","Spanish");
		iso639_language.put("ET","Estonian");
		iso639_language.put("EU","Basque");
		iso639_language.put("FA","Persian");
		iso639_language.put("FI","Finnish");
		iso639_language.put("FJ","Fiji");
		iso639_language.put("FO","Faeroese");
		iso639_language.put("FR","French");
		iso639_language.put("FY","Frisian");
		iso639_language.put("GA","Irish");
		iso639_language.put("GD","Gaelic");
		iso639_language.put("GL","Galician");
		iso639_language.put("GN","Guarani");
		iso639_language.put("GU","Gujarati");
		iso639_language.put("HA","Hausa");
		iso639_language.put("HI","Hindi");
		iso639_language.put("HR","Croatian");
		iso639_language.put("HU","Hungarian");
		iso639_language.put("HY","Armenian");
		iso639_language.put("IA","Interlingua");
		iso639_language.put("IE","Interlingue");
		iso639_language.put("IK","Inupiak");
		iso639_language.put("IN","Indonesian");
		iso639_language.put("IS","Icelandic");
		iso639_language.put("IT","Italian");
		iso639_language.put("IU","Inuktitut"); //added on 10/26/2021 requested by Frank
		iso639_language.put("IW","Hebrew");
		iso639_language.put("JA","Japanese");
		iso639_language.put("JI","Yiddish");
		iso639_language.put("JW","Javanese");
		iso639_language.put("KA","Georgian");
		iso639_language.put("KK","Kazakh");
		iso639_language.put("KL","Greenlandic");
		iso639_language.put("KM","Cambodian");
		iso639_language.put("KN","Kannada");
		iso639_language.put("KO","Korean");
		iso639_language.put("KS","Kashmiri");
		iso639_language.put("KU","Kurdish");
		iso639_language.put("KY","Kirghiz");
		iso639_language.put("LA","Latin");
		iso639_language.put("LN","Lingala");
		iso639_language.put("LO","Laothian");
		iso639_language.put("LT","Lithuanian");
		iso639_language.put("LV","Latvian");
		iso639_language.put("MG","Malagasy");
		iso639_language.put("MI","Maori");
		iso639_language.put("MK","Macedonian");
		iso639_language.put("ML","Malayalam");
		iso639_language.put("MN","Mongolian");
		iso639_language.put("MO","Moldavian");
		iso639_language.put("MR","Marathi");
		iso639_language.put("MS","Malay");
		iso639_language.put("MT","Maltese");
		iso639_language.put("MY","Burmese");
		iso639_language.put("NA","Nauru");
		iso639_language.put("NE","Nepali");
		iso639_language.put("NL","Dutch");
		iso639_language.put("NN","Norwegian (Nynorsk)");
		iso639_language.put("NO","Norwegian");
		iso639_language.put("OC","Occitan");
		iso639_language.put("OM","Oromo");
		iso639_language.put("OR","Oriya");
		iso639_language.put("PA","Punjabi");
		iso639_language.put("PL","Polish");
		iso639_language.put("PS","Pashto");
		iso639_language.put("PT","Portuguese");
		iso639_language.put("QU","Quechua");
		iso639_language.put("RM","Rhaeto-Romance");
		iso639_language.put("RN","Kirundi");
		iso639_language.put("RO","Romanian");
		iso639_language.put("RU","Russian");
		iso639_language.put("RW","Kinyarwanda");
		iso639_language.put("SA","Sanskrit");
		iso639_language.put("SD","Sindhi");
		iso639_language.put("SG","Sangro");
		iso639_language.put("SH","Serbo-Croatian");
		iso639_language.put("SI","Singhalese");
		iso639_language.put("SK","Slovak");
		iso639_language.put("SL","Slovenian");
		iso639_language.put("SM","Samoan");
		iso639_language.put("SN","Shona");
		iso639_language.put("SO","Somali");
		iso639_language.put("SQ","Albanian");
		iso639_language.put("SR","Serbian");
		iso639_language.put("SS","Siswati");
		iso639_language.put("ST","Sesotho");
		iso639_language.put("SU","Sudanese");
		iso639_language.put("SV","Swedish");
		iso639_language.put("SW","Swahili");
		iso639_language.put("TA","Tamil");
		iso639_language.put("TE","Tegulu");
		iso639_language.put("TG","Tajik");
		iso639_language.put("TH","Thai");
		iso639_language.put("TI","Tigrinya");
		iso639_language.put("TK","Turkmen");
		iso639_language.put("TL","Tagalog");
		iso639_language.put("TN","Setswana");
		iso639_language.put("TO","Tonga");
		iso639_language.put("TR","Turkish");
		iso639_language.put("TS","Tsonga");
		iso639_language.put("TT","Tatar");
		iso639_language.put("TW","Twi");
		iso639_language.put("UK","Ukrainian");
		iso639_language.put("UR","Urdu");
		iso639_language.put("UZ","Uzbek");
		iso639_language.put("VI","Vietnamese");
		iso639_language.put("VO","Volapuk");
		iso639_language.put("WO","Wolof");
		iso639_language.put("XH","Xhosa");
		iso639_language.put("YO","Yoruba");
		iso639_language.put("ZH","Chinese");
		iso639_language.put("ZU","Zulu");

		/*Block this old code and use the new code based on EVOPS-1378
		//Language code for OpsbankII three digits
		iso639_language.put("AFR","Afrikaans");
		iso639_language.put("ALB","Albanian");
		iso639_language.put("ARA","Arabic");
		iso639_language.put("ARM","Armenian");
		iso639_language.put("AZE","Azerbaijani");
		iso639_language.put("IND","Indonesian");
		iso639_language.put("BAQ","Basque");
		iso639_language.put("BEN","Bengali");
		iso639_language.put("BOS","Bosnian");
		iso639_language.put("BUL","Bulgarian");
		iso639_language.put("BUR","Burmese");
		iso639_language.put("BEL","Byelorussian");
		iso639_language.put("CAT","Catalan");
		iso639_language.put("CHI","Chinese");
		iso639_language.put("SCR","Croatian");
		iso639_language.put("CZE","Czech");
		iso639_language.put("DAN","Danish");
		iso639_language.put("DUT","Dutch");
		iso639_language.put("ENG","English");
		iso639_language.put("EPO","Esperanto");
		iso639_language.put("EST","Estonian");
		iso639_language.put("FIN","Finnish");
		iso639_language.put("FRE","French");
		iso639_language.put("GLE","Irish");
		iso639_language.put("GLG","Galician");
		iso639_language.put("GEO","Georgian");
		iso639_language.put("GER","German");
		iso639_language.put("GRE","Greek");
		iso639_language.put("HEB","Hebrew");
		iso639_language.put("HIN","Hindi");
		iso639_language.put("HUN","Hungarian");
		iso639_language.put("ICE","Icelandic");
		iso639_language.put("ITA","Italian");
		iso639_language.put("JPN","Japanese");
		iso639_language.put("KOR","Korean");
		iso639_language.put("LAV","Latvian");
		iso639_language.put("LIT","Lithuanian");
		iso639_language.put("MAC","Macedonian");
		iso639_language.put("MAY","Malay");
		iso639_language.put("MAO","Maori");
		iso639_language.put("MON","Mongolian");
		iso639_language.put("NOR","Norwegian");
		iso639_language.put("PER","Persian");
		iso639_language.put("POL","Polish");
		iso639_language.put("MAP","Polyglot");
		iso639_language.put("POR","Portuguese");
		iso639_language.put("PUS","Pushto");
		iso639_language.put("RUM","Romanian");
		iso639_language.put("RUS","Russian");
		iso639_language.put("GLA","Scottish Gaelic");
		iso639_language.put("SCC","Serbian");
		iso639_language.put("SIN","Singhalese");
		iso639_language.put("SLO","Slovak");
		iso639_language.put("SLV","Slovenian");
		iso639_language.put("SPA","Spanish");
		iso639_language.put("SWE","Swedish");
		iso639_language.put("TGL","Tagalog");
		iso639_language.put("THA","Thai");
		iso639_language.put("TUR","Turkish");
		iso639_language.put("UKR","Ukrainian");
		iso639_language.put("URD","Urdu");
		iso639_language.put("UZB","Uzbek");
		iso639_language.put("VIE","Vietnamese");
		*/
		
		//New Language code pre EVOPS-1378 added by hmo at 10/19/2022
		
		iso639_language.put("AAR","Afar");
		iso639_language.put("ABK","Abkhazian");
		iso639_language.put("ACE","Achinese");
		iso639_language.put("ACH","Acoli");
		iso639_language.put("ADA","Adangme");
		iso639_language.put("ADY","Adyghe; Adygei");
		iso639_language.put("AFA","Afro-Asiatic languages");
		iso639_language.put("AFH","Afrihili");
		iso639_language.put("AFR","Afrikaans");
		iso639_language.put("AIN","Ainu");
		iso639_language.put("AKA","Akan");
		iso639_language.put("AKK","Akkadian");
		iso639_language.put("ALB","Albanian");
		iso639_language.put("ALE","Aleut");
		iso639_language.put("ALG","Algonquian languages");
		iso639_language.put("ALT","Southern Altai");
		iso639_language.put("AMH","Amharic");
		iso639_language.put("ANG","English, Old (ca.450-1100)");
		iso639_language.put("ANP","Angika");
		iso639_language.put("APA","Apache languages");
		iso639_language.put("ARA","Arabic");
		iso639_language.put("ARC","Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)");
		iso639_language.put("ARG","Aragonese");
		iso639_language.put("ARM","Armenian");
		iso639_language.put("ARN","Mapudungun; Mapuche");
		iso639_language.put("ARP","Arapaho");
		iso639_language.put("ART","Artificial languages");
		iso639_language.put("ARW","Arawak");
		iso639_language.put("ASM","Assamese");
		iso639_language.put("AST","Asturian; Bable; Leonese; Asturleonese");
		iso639_language.put("ATH","Athapascan languages");
		iso639_language.put("AUS","Australian languages");
		iso639_language.put("AVA","Avaric");
		iso639_language.put("AVE","Avestan");
		iso639_language.put("AWA","Awadhi");
		iso639_language.put("AYM","Aymara");
		iso639_language.put("AZE","Azerbaijani");
		iso639_language.put("BAD","Banda languages");
		iso639_language.put("BAI","Bamileke languages");
		iso639_language.put("BAK","Bashkir");
		iso639_language.put("BAL","Baluchi");
		iso639_language.put("BAM","Bambara");
		iso639_language.put("BAN","Balinese");
		iso639_language.put("BAQ","Basque");
		iso639_language.put("BAS","Basa");
		iso639_language.put("BAT","Baltic languages");
		iso639_language.put("BEJ","Beja; Bedawiyet");
		iso639_language.put("BEL","Belarusian");
		iso639_language.put("BEM","Bemba");
		iso639_language.put("BEN","Bengali");
		iso639_language.put("BER","Berber languages");
		iso639_language.put("BHO","Bhojpuri");
		iso639_language.put("BIH","Bihari languages");
		iso639_language.put("BIK","Bikol");
		iso639_language.put("BIN","Bini; Edo");
		iso639_language.put("BIS","Bislama");
		iso639_language.put("BLA","Siksika");
		iso639_language.put("BNT","Bantu languages");
		iso639_language.put("BOS","Bosnian");
		iso639_language.put("BRA","Braj");
		iso639_language.put("BRE","Breton");
		iso639_language.put("BTK","Batak languages");
		iso639_language.put("BUA","Buriat");
		iso639_language.put("BUG","Buginese");
		iso639_language.put("BUL","Bulgarian");
		iso639_language.put("BUR","Burmese");
		iso639_language.put("BYN","Blin; Bilin");
		iso639_language.put("CAD","Caddo");
		iso639_language.put("CAI","Central American Indian languages");
		iso639_language.put("CAR","Galibi Carib");
		iso639_language.put("CAT","Catalan; Valencian");
		iso639_language.put("CAU","Caucasian languages");
		iso639_language.put("CEB","Cebuano");
		iso639_language.put("CEL","Celtic languages");
		iso639_language.put("CHA","Chamorro");
		iso639_language.put("CHB","Chibcha");
		iso639_language.put("CHE","Chechen");
		iso639_language.put("CHG","Chagatai");
		iso639_language.put("CHI","Chinese");
		iso639_language.put("CHK","Chuukese");
		iso639_language.put("CHM","Mari");
		iso639_language.put("CHN","Chinook jargon");
		iso639_language.put("CHO","Choctaw");
		iso639_language.put("CHP","Chipewyan; Dene Suline");
		iso639_language.put("CHR","Cherokee");
		iso639_language.put("CHU","Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic");
		iso639_language.put("CHV","Chuvash");
		iso639_language.put("CHY","Cheyenne");
		iso639_language.put("CMC","Chamic languages");
		iso639_language.put("CNR","Montenegrin");
		iso639_language.put("COP","Coptic");
		iso639_language.put("COR","Cornish");
		iso639_language.put("COS","Corsican");
		iso639_language.put("CPE","Creoles and pidgins, English based");
		iso639_language.put("CPF","Creoles and pidgins, French-based");
		iso639_language.put("CPP","Creoles and pidgins, Portuguese-based");
		iso639_language.put("CRE","Cree");
		iso639_language.put("CRH","Crimean Tatar; Crimean Turkish");
		iso639_language.put("CRP","Creoles and pidgins");
		iso639_language.put("CSB","Kashubian");
		iso639_language.put("CUS","Cushitic languages");
		iso639_language.put("CZE","Czech");
		iso639_language.put("DAK","Dakota");
		iso639_language.put("DAN","Danish");
		iso639_language.put("DAR","Dargwa");
		iso639_language.put("DAY","Land Dayak languages");
		iso639_language.put("DEL","Delaware");
		iso639_language.put("DEN","Slave (Athapascan)");
		iso639_language.put("DGR","Dogrib");
		iso639_language.put("DIN","Dinka");
		iso639_language.put("DIV","Divehi; Dhivehi; Maldivian");
		iso639_language.put("DOI","Dogri");
		iso639_language.put("DRA","Dravidian languages");
		iso639_language.put("DSB","Lower Sorbian");
		iso639_language.put("DUA","Duala");
		iso639_language.put("DUM","Dutch, Middle (ca.1050-1350)");
		iso639_language.put("DUT","Dutch; Flemish");
		iso639_language.put("DYU","Dyula");
		iso639_language.put("DZO","Dzongkha");
		iso639_language.put("EFI","Efik");
		iso639_language.put("EGY","Egyptian (Ancient)");
		iso639_language.put("EKA","Ekajuk");
		iso639_language.put("ELX","Elamite");
		iso639_language.put("ENG","English");
		iso639_language.put("ENM","English, Middle (1100-1500)");
		iso639_language.put("EPO","Esperanto");
		iso639_language.put("EST","Estonian");
		iso639_language.put("EWE","Ewe");
		iso639_language.put("EWO","Ewondo");
		iso639_language.put("FAN","Fang");
		iso639_language.put("FAO","Faroese");
		iso639_language.put("FAT","Fanti");
		iso639_language.put("FIJ","Fijian");
		iso639_language.put("FIL","Filipino; Pilipino");
		iso639_language.put("FIN","Finnish");
		iso639_language.put("FIU","Finno-Ugrian languages");
		iso639_language.put("FON","Fon");
		iso639_language.put("FRE","French");
		iso639_language.put("FRM","French, Middle (ca.1400-1600)");
		iso639_language.put("FRO","French, Old (842-ca.1400)");
		iso639_language.put("FRR","Northern Frisian");
		iso639_language.put("FRS","Eastern Frisian");
		iso639_language.put("FRY","Western Frisian");
		iso639_language.put("FUL","Fulah");
		iso639_language.put("FUR","Friulian");
		iso639_language.put("GAA","Ga");
		iso639_language.put("GAY","Gayo");
		iso639_language.put("GBA","Gbaya");
		iso639_language.put("GEM","Germanic languages");
		iso639_language.put("GEO","Georgian");
		iso639_language.put("GER","German");
		iso639_language.put("GEZ","Geez");
		iso639_language.put("GIL","Gilbertese");
		iso639_language.put("GLA","Gaelic; Scottish Gaelic");
		iso639_language.put("GLE","Irish");
		iso639_language.put("GLG","Galician");
		iso639_language.put("GLV","Manx");
		iso639_language.put("GMH","German, Middle High (ca.1050-1500)");
		iso639_language.put("GOH","German, Old High (ca.750-1050)");
		iso639_language.put("GON","Gondi");
		iso639_language.put("GOR","Gorontalo");
		iso639_language.put("GOT","Gothic");
		iso639_language.put("GRB","Grebo");
		iso639_language.put("GRC","Greek, Ancient (to 1453)");
		iso639_language.put("GRE","Greek, Modern (1453-)");
		iso639_language.put("GRN","Guarani");
		iso639_language.put("GSW","Swiss German; Alemannic; Alsatian");
		iso639_language.put("GUJ","Gujarati");
		iso639_language.put("GWI","Gwich'in");
		iso639_language.put("HAI","Haida");
		iso639_language.put("HAT","Haitian; Haitian Creole");
		iso639_language.put("HAU","Hausa");
		iso639_language.put("HAW","Hawaiian");
		iso639_language.put("HEB","Hebrew");
		iso639_language.put("HER","Herero");
		iso639_language.put("HIL","Hiligaynon");
		iso639_language.put("HIM","Himachali languages; Western Pahari languages");
		iso639_language.put("HIN","Hindi");
		iso639_language.put("HIT","Hittite");
		iso639_language.put("HMN","Hmong; Mong");
		iso639_language.put("HMO","Hiri Motu");
		iso639_language.put("HRV","Croatian");
		iso639_language.put("HSB","Upper Sorbian");
		iso639_language.put("HUN","Hungarian");
		iso639_language.put("HUP","Hupa");
		iso639_language.put("IBA","Iban");
		iso639_language.put("IBO","Igbo");
		iso639_language.put("ICE","Icelandic");
		iso639_language.put("IDO","Ido");
		iso639_language.put("III","Sichuan Yi; Nuosu");
		iso639_language.put("IJO","Ijo languages");
		iso639_language.put("IKU","Inuktitut");
		iso639_language.put("ILE","Interlingue; Occidental");
		iso639_language.put("ILO","Iloko");
		iso639_language.put("INA","Interlingua (International Auxiliary Language Association)");
		iso639_language.put("INC","Indic languages");
		iso639_language.put("IND","Indonesian");
		iso639_language.put("INE","Indo-European languages");
		iso639_language.put("INH","Ingush");
		iso639_language.put("IPK","Inupiaq");
		iso639_language.put("IRA","Iranian languages");
		iso639_language.put("IRO","Iroquoian languages");
		iso639_language.put("ITA","Italian");
		iso639_language.put("JAV","Javanese");
		iso639_language.put("JBO","Lojban");
		iso639_language.put("JPN","Japanese");
		iso639_language.put("JPR","Judeo-Persian");
		iso639_language.put("JRB","Judeo-Arabic");
		iso639_language.put("KAA","Kara-Kalpak");
		iso639_language.put("KAB","Kabyle");
		iso639_language.put("KAC","Kachin; Jingpho");
		iso639_language.put("KAL","Kalaallisut; Greenlandic");
		iso639_language.put("KAM","Kamba");
		iso639_language.put("KAN","Kannada");
		iso639_language.put("KAR","Karen languages");
		iso639_language.put("KAS","Kashmiri");
		iso639_language.put("KAU","Kanuri");
		iso639_language.put("KAW","Kawi");
		iso639_language.put("KAZ","Kazakh");
		iso639_language.put("KBD","Kabardian");
		iso639_language.put("KHA","Khasi");
		iso639_language.put("KHI","Khoisan languages");
		iso639_language.put("KHM","Central Khmer");
		iso639_language.put("KHO","Khotanese; Sakan");
		iso639_language.put("KIK","Kikuyu; Gikuyu");
		iso639_language.put("KIN","Kinyarwanda");
		iso639_language.put("KIR","Kirghiz; Kyrgyz");
		iso639_language.put("KMB","Kimbundu");
		iso639_language.put("KOK","Konkani");
		iso639_language.put("KOM","Komi");
		iso639_language.put("KON","Kongo");
		iso639_language.put("KOR","Korean");
		iso639_language.put("KOS","Kosraean");
		iso639_language.put("KPE","Kpelle");
		iso639_language.put("KRC","Karachay-Balkar");
		iso639_language.put("KRL","Karelian");
		iso639_language.put("KRO","Kru languages");
		iso639_language.put("KRU","Kurukh");
		iso639_language.put("KUA","Kuanyama; Kwanyama");
		iso639_language.put("KUM","Kumyk");
		iso639_language.put("KUR","Kurdish");
		iso639_language.put("KUT","Kutenai");
		iso639_language.put("LAD","Ladino");
		iso639_language.put("LAH","Lahnda");
		iso639_language.put("LAM","Lamba");
		iso639_language.put("LAO","Lao");
		iso639_language.put("LAT","Latin");
		iso639_language.put("LAV","Latvian");
		iso639_language.put("LEZ","Lezghian");
		iso639_language.put("LIM","Limburgan; Limburger; Limburgish");
		iso639_language.put("LIN","Lingala");
		iso639_language.put("LIT","Lithuanian");
		iso639_language.put("LOL","Mongo");
		iso639_language.put("LOZ","Lozi");
		iso639_language.put("LTZ","Luxembourgish; Letzeburgesch");
		iso639_language.put("LUA","Luba-Lulua");
		iso639_language.put("LUB","Luba-Katanga");
		iso639_language.put("LUG","Ganda");
		iso639_language.put("LUI","Luiseno");
		iso639_language.put("LUN","Lunda");
		iso639_language.put("LUO","Luo (Kenya and Tanzania)");
		iso639_language.put("LUS","Lushai");
		iso639_language.put("MAC","Macedonian");
		iso639_language.put("MAD","Madurese");
		iso639_language.put("MAG","Magahi");
		iso639_language.put("MAH","Marshallese");
		iso639_language.put("MAI","Maithili");
		iso639_language.put("MAK","Makasar");
		iso639_language.put("MAL","Malayalam");
		iso639_language.put("MAN","Mandingo");
		iso639_language.put("MAO","Maori");
		iso639_language.put("MAP","Austronesian languages");
		iso639_language.put("MAR","Marathi");
		iso639_language.put("MAS","Masai");
		iso639_language.put("MAY","Malay");
		iso639_language.put("MDF","Moksha");
		iso639_language.put("MDR","Mandar");
		iso639_language.put("MEN","Mende");
		iso639_language.put("MGA","Irish, Middle (900-1200)");
		iso639_language.put("MIC","Mi'kmaq; Micmac");
		iso639_language.put("MIN","Minangkabau");
		iso639_language.put("MIS","Uncoded languages");
		iso639_language.put("MKH","Mon-Khmer languages");
		iso639_language.put("MLG","Malagasy");
		iso639_language.put("MLT","Maltese");
		iso639_language.put("MNC","Manchu");
		iso639_language.put("MNI","Manipuri");
		iso639_language.put("MNO","Manobo languages");
		iso639_language.put("MOH","Mohawk");
		iso639_language.put("MON","Mongolian");
		iso639_language.put("MOS","Mossi");
		iso639_language.put("MUL","Multiple languages");
		iso639_language.put("MUN","Munda languages");
		iso639_language.put("MUS","Creek");
		iso639_language.put("MWL","Mirandese");
		iso639_language.put("MWR","Marwari");
		iso639_language.put("MYN","Mayan languages");
		iso639_language.put("MYV","Erzya");
		iso639_language.put("NAH","Nahuatl languages");
		iso639_language.put("NAI","North American Indian languages");
		iso639_language.put("NAP","Neapolitan");
		iso639_language.put("NAU","Nauru");
		iso639_language.put("NAV","Navajo; Navaho");
		iso639_language.put("NBL","Ndebele, South; South Ndebele");
		iso639_language.put("NDE","Ndebele, North; North Ndebele");
		iso639_language.put("NDO","Ndonga");
		iso639_language.put("NDS","Low German; Low Saxon; German, Low; Saxon, Low");
		iso639_language.put("NEP","Nepali");
		iso639_language.put("NEW","Nepal Bhasa; Newari");
		iso639_language.put("NIA","Nias");
		iso639_language.put("NIC","Niger-Kordofanian languages");
		iso639_language.put("NIU","Niuean");
		iso639_language.put("NNO","Norwegian Nynorsk; Nynorsk, Norwegian");
		iso639_language.put("NOB","Bokmål, Norwegian; Norwegian Bokmål");
		iso639_language.put("NOG","Nogai");
		iso639_language.put("NON","Norse, Old");
		iso639_language.put("NOR","Norwegian");
		iso639_language.put("NQO","N'Ko");
		iso639_language.put("NSO","Pedi; Sepedi; Northern Sotho");
		iso639_language.put("NUB","Nubian languages");
		iso639_language.put("NWC","Classical Newari; Old Newari; Classical Nepal Bhasa");
		iso639_language.put("NYA","Chichewa; Chewa; Nyanja");
		iso639_language.put("NYM","Nyamwezi");
		iso639_language.put("NYN","Nyankole");
		iso639_language.put("NYO","Nyoro");
		iso639_language.put("NZI","Nzima");
		iso639_language.put("OCI","Occitan (post 1500)");
		iso639_language.put("OJI","Ojibwa");
		iso639_language.put("ORI","Oriya");
		iso639_language.put("ORM","Oromo");
		iso639_language.put("OSA","Osage");
		iso639_language.put("OSS","Ossetian; Ossetic");
		iso639_language.put("OTA","Turkish, Ottoman (1500-1928)");
		iso639_language.put("OTO","Otomian languages");
		iso639_language.put("PAA","Papuan languages");
		iso639_language.put("PAG","Pangasinan");
		iso639_language.put("PAL","Pahlavi");
		iso639_language.put("PAM","Pampanga; Kapampangan");
		iso639_language.put("PAN","Panjabi; Punjabi");
		iso639_language.put("PAP","Papiamento");
		iso639_language.put("PAU","Palauan");
		iso639_language.put("PEO","Persian, Old (ca.600-400 B.C.)");
		iso639_language.put("PER","Persian");
		iso639_language.put("PHI","Philippine languages");
		iso639_language.put("PHN","Phoenician");
		iso639_language.put("PLI","Pali");
		iso639_language.put("POL","Polish");
		iso639_language.put("PON","Pohnpeian");
		iso639_language.put("POR","Portuguese");
		iso639_language.put("PRA","Prakrit languages");
		iso639_language.put("PRO","Provençal, Old (to 1500); Occitan, Old (to 1500)");
		iso639_language.put("PUS","Pushto; Pashto");
		iso639_language.put("QUE","Quechua");
		iso639_language.put("RAJ","Rajasthani");
		iso639_language.put("RAP","Rapanui");
		iso639_language.put("RAR","Rarotongan; Cook Islands Maori");
		iso639_language.put("ROA","Romance languages");
		iso639_language.put("ROH","Romansh");
		iso639_language.put("ROM","Romany");
		iso639_language.put("RUM","Romanian; Moldavian; Moldovan");
		iso639_language.put("RUN","Rundi");
		iso639_language.put("RUP","Aromanian; Arumanian; Macedo-Romanian");
		iso639_language.put("RUS","Russian");
		iso639_language.put("SAD","Sandawe");
		iso639_language.put("SAG","Sango");
		iso639_language.put("SAH","Yakut");
		iso639_language.put("SAI","South American Indian languages");
		iso639_language.put("SAL","Salishan languages");
		iso639_language.put("SAM","Samaritan Aramaic");
		iso639_language.put("SAN","Sanskrit");
		iso639_language.put("SAS","Sasak");
		iso639_language.put("SAT","Santali");
		iso639_language.put("SCN","Sicilian");
		iso639_language.put("SCO","Scots");
		iso639_language.put("SEL","Selkup");
		iso639_language.put("SEM","Semitic languages");
		iso639_language.put("SGA","Irish, Old (to 900)");
		iso639_language.put("SGN","Sign Languages");
		iso639_language.put("SHN","Shan");
		iso639_language.put("SID","Sidamo");
		iso639_language.put("SIN","Sinhala; Sinhalese");
		iso639_language.put("SIO","Siouan languages");
		iso639_language.put("SIT","Sino-Tibetan languages");
		iso639_language.put("SLA","Slavic languages");
		iso639_language.put("SLO","Slovak");
		iso639_language.put("SLV","Slovenian");
		iso639_language.put("SMA","Southern Sami");
		iso639_language.put("SME","Northern Sami");
		iso639_language.put("SMI","Sami languages");
		iso639_language.put("SMJ","Lule Sami");
		iso639_language.put("SMN","Inari Sami");
		iso639_language.put("SMO","Samoan");
		iso639_language.put("SMS","Skolt Sami");
		iso639_language.put("SNA","Shona");
		iso639_language.put("SND","Sindhi");
		iso639_language.put("SNK","Soninke");
		iso639_language.put("SOG","Sogdian");
		iso639_language.put("SOM","Somali");
		iso639_language.put("SON","Songhai languages");
		iso639_language.put("SOT","Sotho, Southern");
		iso639_language.put("SPA","Spanish; Castilian");
		iso639_language.put("SRD","Sardinian");
		iso639_language.put("SRN","Sranan Tongo");
		iso639_language.put("SRP","Serbian");
		iso639_language.put("SRR","Serer");
		iso639_language.put("SSA","Nilo-Saharan languages");
		iso639_language.put("SSW","Swati");
		iso639_language.put("SUK","Sukuma");
		iso639_language.put("SUN","Sundanese");
		iso639_language.put("SUS","Susu");
		iso639_language.put("SUX","Sumerian");
		iso639_language.put("SWA","Swahili");
		iso639_language.put("SWE","Swedish");
		iso639_language.put("SYC","Classical Syriac");
		iso639_language.put("SYR","Syriac");
		iso639_language.put("TAH","Tahitian");
		iso639_language.put("TAI","Tai languages");
		iso639_language.put("TAM","Tamil");
		iso639_language.put("TAT","Tatar");
		iso639_language.put("TEL","Telugu");
		iso639_language.put("TEM","Timne");
		iso639_language.put("TER","Tereno");
		iso639_language.put("TET","Tetum");
		iso639_language.put("TGK","Tajik");
		iso639_language.put("TGL","Tagalog");
		iso639_language.put("THA","Thai");
		iso639_language.put("TIB","Tibetan");
		iso639_language.put("TIG","Tigre");
		iso639_language.put("TIR","Tigrinya");
		iso639_language.put("TIV","Tiv");
		iso639_language.put("TKL","Tokelau");
		iso639_language.put("TLH","Klingon; tlhIngan-Hol");
		iso639_language.put("TLI","Tlingit");
		iso639_language.put("TMH","Tamashek");
		iso639_language.put("TOG","Tonga (Nyasa)");
		iso639_language.put("TON","Tonga (Tonga Islands)");
		iso639_language.put("TPI","Tok Pisin");
		iso639_language.put("TSI","Tsimshian");
		iso639_language.put("TSN","Tswana");
		iso639_language.put("TSO","Tsonga");
		iso639_language.put("TUK","Turkmen");
		iso639_language.put("TUM","Tumbuka");
		iso639_language.put("TUP","Tupi languages");
		iso639_language.put("TUR","Turkish");
		iso639_language.put("TUT","Altaic languages");
		iso639_language.put("TVL","Tuvalu");
		iso639_language.put("TWI","Twi");
		iso639_language.put("TYV","Tuvinian");
		iso639_language.put("UDM","Udmurt");
		iso639_language.put("UGA","Ugaritic");
		iso639_language.put("UIG","Uighur; Uyghur");
		iso639_language.put("UKR","Ukrainian");
		iso639_language.put("UMB","Umbundu");
		iso639_language.put("UND","Undetermined");
		iso639_language.put("URD","Urdu");
		iso639_language.put("UZB","Uzbek");
		iso639_language.put("VAI","Vai");
		iso639_language.put("VEN","Venda");
		iso639_language.put("VIE","Vietnamese");
		iso639_language.put("VOL","Volapük");
		iso639_language.put("VOT","Votic");
		iso639_language.put("WAK","Wakashan languages");
		iso639_language.put("WAL","Wolaitta; Wolaytta");
		iso639_language.put("WAR","Waray");
		iso639_language.put("WAS","Washo");
		iso639_language.put("WEL","Welsh");
		iso639_language.put("WEN","Sorbian languages");
		iso639_language.put("WLN","Walloon");
		iso639_language.put("WOL","Wolof");
		iso639_language.put("XAL","Kalmyk; Oirat");
		iso639_language.put("XHO","Xhosa");
		iso639_language.put("YAO","Yao");
		iso639_language.put("YAP","Yapese");
		iso639_language.put("YID","Yiddish");
		iso639_language.put("YOR","Yoruba");
		iso639_language.put("YPK","Yupik languages");
		iso639_language.put("ZAP","Zapotec");
		iso639_language.put("ZBL","Blissymbols; Blissymbolics; Bliss");
		iso639_language.put("ZEN","Zenaga");
		iso639_language.put("ZGH","Standard Moroccan Tamazight");
		iso639_language.put("ZHA","Zhuang; Chuang");
		iso639_language.put("ZND","Zande languages");
		iso639_language.put("ZUL","Zulu");
		iso639_language.put("ZUN","Zuni");
		iso639_language.put("ZXX","No linguistic content; Not applicable");
		iso639_language.put("ZZA","Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki");

		//Language code for OpsbankII four digits
		iso639_language.put("AFRK","Afrikaans");
		iso639_language.put("ALBA","Albanian");
		iso639_language.put("ARAB","Arabic");
		iso639_language.put("ARME","Armenian");
		iso639_language.put("AZRB","Azerbaijani");
		iso639_language.put("BAHA","Indonesian");
		iso639_language.put("BASQ","Basque");
		iso639_language.put("BENG","Bengali");
		iso639_language.put("BOSN","Bosnian");
		iso639_language.put("BULG","Bulgarian");
		iso639_language.put("BURM","Burmese");
		iso639_language.put("BYEL","Byelorussian");
		iso639_language.put("CATA","Catalan");
		iso639_language.put("CHIN","Chinese");
		iso639_language.put("CROA","Croatian");
		iso639_language.put("CZEH","Czech");
		iso639_language.put("DANS","Danish");
		iso639_language.put("DUTC","Dutch");
		iso639_language.put("ENGL","English");
		iso639_language.put("ESPE","Esperanto");
		iso639_language.put("ESTO","Estonian");
		iso639_language.put("FINN","Finnish");
		iso639_language.put("FREN","French");
		iso639_language.put("GAEL","Irish");
		iso639_language.put("GALL","Galician");
		iso639_language.put("GEOR","Georgian");
		iso639_language.put("GERM","German");
		iso639_language.put("GREK","Greek");
		iso639_language.put("HEBR","Hebrew");
		iso639_language.put("INDI","Hindi");
		iso639_language.put("HUNG","Hungarian");
		iso639_language.put("ICEL","Icelandic");
		iso639_language.put("ITAL","Italian");
		iso639_language.put("JAPA","Japanese");
		iso639_language.put("KORA","Korean");
		iso639_language.put("LATV","Latvian");
		iso639_language.put("LITH","Lithuanian");
		iso639_language.put("MACE","Macedonian");
		iso639_language.put("MALA","Malay");
		iso639_language.put("MAOR","Maori");
		iso639_language.put("MONG","Mongolian");
		iso639_language.put("NORW","Norwegian");
		iso639_language.put("PERS","Persian");
		iso639_language.put("POLS","Polish");
		iso639_language.put("POLY","Polyglot");
		iso639_language.put("PORT","Portuguese");
		iso639_language.put("PUSH","Pushto");
		iso639_language.put("RUMA","Romanian");
		iso639_language.put("RUSS","Russian");
		iso639_language.put("SCOT","Scottish Gaelic");
		iso639_language.put("SERB","Serbian");
		iso639_language.put("SINH","Singhalese");
		iso639_language.put("SLVK","Slovak");
		iso639_language.put("SLVN","Slovenian");
		iso639_language.put("SPAN","Spanish");
		iso639_language.put("SWED","Swedish");
		iso639_language.put("TAGA","Tagalog");
		iso639_language.put("THAI","Thai");
		iso639_language.put("TURK","Turkish");
		iso639_language.put("UKRA","Ukrainian");
		iso639_language.put("URDU","Urdu");
		iso639_language.put("UZBE","Uzbek");
		iso639_language.put("VIET","Vietnamese");

	}

	public static String getIso639Language(String code)
	{
		String lName = null;
		lName = (String)iso639_language.get(code.toUpperCase());
		if(lName==null)
		{
			lName = code;
		}
		return lName.toString();
	}

}
